using System;
using Google.ProtocolBuffers.Descriptors;
using Google.ProtocolBuffers.FieldAccess;

namespace Google.ProtocolBuffers.DescriptorProtos;

public static class DescriptorProtoFile
{
	internal static MessageDescriptor internal__static_google_protobuf_FileDescriptorSet__Descriptor;

	internal static FieldAccessorTable<FileDescriptorSet, FileDescriptorSet.Builder> internal__static_google_protobuf_FileDescriptorSet__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_FileDescriptorProto__Descriptor;

	internal static FieldAccessorTable<FileDescriptorProto, FileDescriptorProto.Builder> internal__static_google_protobuf_FileDescriptorProto__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_DescriptorProto__Descriptor;

	internal static FieldAccessorTable<DescriptorProto, DescriptorProto.Builder> internal__static_google_protobuf_DescriptorProto__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_DescriptorProto_ExtensionRange__Descriptor;

	internal static FieldAccessorTable<DescriptorProto.Types.ExtensionRange, DescriptorProto.Types.ExtensionRange.Builder> internal__static_google_protobuf_DescriptorProto_ExtensionRange__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_FieldDescriptorProto__Descriptor;

	internal static FieldAccessorTable<FieldDescriptorProto, FieldDescriptorProto.Builder> internal__static_google_protobuf_FieldDescriptorProto__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_EnumDescriptorProto__Descriptor;

	internal static FieldAccessorTable<EnumDescriptorProto, EnumDescriptorProto.Builder> internal__static_google_protobuf_EnumDescriptorProto__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_EnumValueDescriptorProto__Descriptor;

	internal static FieldAccessorTable<EnumValueDescriptorProto, EnumValueDescriptorProto.Builder> internal__static_google_protobuf_EnumValueDescriptorProto__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_ServiceDescriptorProto__Descriptor;

	internal static FieldAccessorTable<ServiceDescriptorProto, ServiceDescriptorProto.Builder> internal__static_google_protobuf_ServiceDescriptorProto__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_MethodDescriptorProto__Descriptor;

	internal static FieldAccessorTable<MethodDescriptorProto, MethodDescriptorProto.Builder> internal__static_google_protobuf_MethodDescriptorProto__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_FileOptions__Descriptor;

	internal static FieldAccessorTable<FileOptions, FileOptions.Builder> internal__static_google_protobuf_FileOptions__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_MessageOptions__Descriptor;

	internal static FieldAccessorTable<MessageOptions, MessageOptions.Builder> internal__static_google_protobuf_MessageOptions__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_FieldOptions__Descriptor;

	internal static FieldAccessorTable<FieldOptions, FieldOptions.Builder> internal__static_google_protobuf_FieldOptions__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_EnumOptions__Descriptor;

	internal static FieldAccessorTable<EnumOptions, EnumOptions.Builder> internal__static_google_protobuf_EnumOptions__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_EnumValueOptions__Descriptor;

	internal static FieldAccessorTable<EnumValueOptions, EnumValueOptions.Builder> internal__static_google_protobuf_EnumValueOptions__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_ServiceOptions__Descriptor;

	internal static FieldAccessorTable<ServiceOptions, ServiceOptions.Builder> internal__static_google_protobuf_ServiceOptions__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_MethodOptions__Descriptor;

	internal static FieldAccessorTable<MethodOptions, MethodOptions.Builder> internal__static_google_protobuf_MethodOptions__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_UninterpretedOption__Descriptor;

	internal static FieldAccessorTable<UninterpretedOption, UninterpretedOption.Builder> internal__static_google_protobuf_UninterpretedOption__FieldAccessorTable;

	internal static MessageDescriptor internal__static_google_protobuf_UninterpretedOption_NamePart__Descriptor;

	internal static FieldAccessorTable<UninterpretedOption.Types.NamePart, UninterpretedOption.Types.NamePart.Builder> internal__static_google_protobuf_UninterpretedOption_NamePart__FieldAccessorTable;

	private static FileDescriptor descriptor;

	public static FileDescriptor Descriptor => descriptor;

	public static void RegisterAllExtensions(ExtensionRegistry registry)
	{
	}

	static DescriptorProtoFile()
	{
		byte[] descriptorData = Convert.FromBase64String("CiBnb29nbGUvcHJvdG9idWYvZGVzY3JpcHRvci5wcm90bxIPZ29vZ2xlLnByb3RvYnVmIkcKEUZpbGVEZXNjcmlwdG9yU2V0EjIKBGZpbGUYASADKAsyJC5nb29nbGUucHJvdG9idWYuRmlsZURlc2NyaXB0b3JQcm90byLcAgoTRmlsZURlc2NyaXB0b3JQcm90bxIMCgRuYW1lGAEgASgJEg8KB3BhY2thZ2UYAiABKAkSEgoKZGVwZW5kZW5jeRgDIAMoCRI2CgxtZXNzYWdlX3R5cGUYBCADKAsyIC5nb29nbGUucHJvdG9idWYuRGVzY3JpcHRvclByb3RvEjcKCWVudW1fdHlwZRgFIAMoCzIkLmdvb2dsZS5wcm90b2J1Zi5FbnVtRGVzY3JpcHRvclByb3RvEjgKB3NlcnZpY2UYBiADKAsyJy5nb29nbGUucHJvdG9idWYuU2VydmljZURlc2NyaXB0b3JQcm90bxI4CglleHRlbnNpb24YByADKAsyJS5nb29nbGUucHJvdG9idWYuRmllbGREZXNjcmlwdG9yUHJvdG8SLQoHb3B0aW9ucxgIIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucyKpAwoPRGVzY3JpcHRvclByb3RvEgwKBG5hbWUYASABKAkSNAoFZmllbGQYAiADKAsyJS5nb29nbGUucHJvdG9idWYuRmllbGREZXNjcmlwdG9yUHJvdG8SOAoJZXh0ZW5zaW9uGAYgAygLMiUuZ29vZ2xlLnByb3RvYnVmLkZpZWxkRGVzY3JpcHRvclByb3RvEjUKC25lc3RlZF90eXBlGAMgAygLMiAuZ29vZ2xlLnByb3RvYnVmLkRlc2NyaXB0b3JQcm90bxI3CgllbnVtX3R5cGUYBCADKAsyJC5nb29nbGUucHJvdG9idWYuRW51bURlc2NyaXB0b3JQcm90bxJICg9leHRlbnNpb25fcmFuZ2UYBSADKAsyLy5nb29nbGUucHJvdG9idWYuRGVzY3JpcHRvclByb3RvLkV4dGVuc2lvblJhbmdlEjAKB29wdGlvbnMYByABKAsyHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMaLAoORXh0ZW5zaW9uUmFuZ2USDQoFc3RhcnQYASABKAUSCwoDZW5kGAIgASgFIpQFChRGaWVsZERlc2NyaXB0b3JQcm90bxIMCgRuYW1lGAEgASgJEg4KBm51bWJlchgDIAEoBRI6CgVsYWJlbBgEIAEoDjIrLmdvb2dsZS5wcm90b2J1Zi5GaWVsZERlc2NyaXB0b3JQcm90by5MYWJlbBI4CgR0eXBlGAUgASgOMiouZ29vZ2xlLnByb3RvYnVmLkZpZWxkRGVzY3JpcHRvclByb3RvLlR5cGUSEQoJdHlwZV9uYW1lGAYgASgJEhAKCGV4dGVuZGVlGAIgASgJEhUKDWRlZmF1bHRfdmFsdWUYByABKAkSLgoHb3B0aW9ucxgIIAEoCzIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMitgIKBFR5cGUSDwoLVFlQRV9ET1VCTEUQARIOCgpUWVBFX0ZMT0FUEAISDgoKVFlQRV9JTlQ2NBADEg8KC1RZUEVfVUlOVDY0EAQSDgoKVFlQRV9JTlQzMhAFEhAKDFRZUEVfRklYRUQ2NBAGEhAKDFRZUEVfRklYRUQzMhAHEg0KCVRZUEVfQk9PTBAIEg8KC1RZUEVfU1RSSU5HEAkSDgoKVFlQRV9HUk9VUBAKEhAKDFRZUEVfTUVTU0FHRRALEg4KClRZUEVfQllURVMQDBIPCgtUWVBFX1VJTlQzMhANEg0KCVRZUEVfRU5VTRAOEhEKDVRZUEVfU0ZJWEVEMzIQDxIRCg1UWVBFX1NGSVhFRDY0EBASDwoLVFlQRV9TSU5UMzIQERIPCgtUWVBFX1NJTlQ2NBASIkMKBUxhYmVsEhIKDkxBQkVMX09QVElPTkFMEAESEgoOTEFCRUxfUkVRVUlSRUQQAhISCg5MQUJFTF9SRVBFQVRFRBADIowBChNFbnVtRGVzY3JpcHRvclByb3RvEgwKBG5hbWUYASABKAkSOAoFdmFsdWUYAiADKAsyKS5nb29nbGUucHJvdG9idWYuRW51bVZhbHVlRGVzY3JpcHRvclByb3RvEi0KB29wdGlvbnMYAyABKAsyHC5nb29nbGUucHJvdG9idWYuRW51bU9wdGlvbnMibAoYRW51bVZhbHVlRGVzY3JpcHRvclByb3RvEgwKBG5hbWUYASABKAkSDgoGbnVtYmVyGAIgASgFEjIKB29wdGlvbnMYAyABKAsyIS5nb29nbGUucHJvdG9idWYuRW51bVZhbHVlT3B0aW9ucyKQAQoWU2VydmljZURlc2NyaXB0b3JQcm90bxIMCgRuYW1lGAEgASgJEjYKBm1ldGhvZBgCIAMoCzImLmdvb2dsZS5wcm90b2J1Zi5NZXRob2REZXNjcmlwdG9yUHJvdG8SMAoHb3B0aW9ucxgDIAEoCzIfLmdvb2dsZS5wcm90b2J1Zi5TZXJ2aWNlT3B0aW9ucyJ/ChVNZXRob2REZXNjcmlwdG9yUHJvdG8SDAoEbmFtZRgBIAEoCRISCgppbnB1dF90eXBlGAIgASgJEhMKC291dHB1dF90eXBlGAMgASgJEi8KB29wdGlvbnMYBCABKAsyHi5nb29nbGUucHJvdG9idWYuTWV0aG9kT3B0aW9ucyKnAgoLRmlsZU9wdGlvbnMSFAoMamF2YV9wYWNrYWdlGAEgASgJEhwKFGphdmFfb3V0ZXJfY2xhc3NuYW1lGAggASgJEiIKE2phdmFfbXVsdGlwbGVfZmlsZXMYCiABKAg6BWZhbHNlEkYKDG9wdGltaXplX2ZvchgJIAEoDjIpLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucy5PcHRpbWl6ZU1vZGU6BVNQRUVEEkMKFHVuaW50ZXJwcmV0ZWRfb3B0aW9uGOcHIAMoCzIkLmdvb2dsZS5wcm90b2J1Zi5VbmludGVycHJldGVkT3B0aW9uIigKDE9wdGltaXplTW9kZRIJCgVTUEVFRBABEg0KCUNPREVfU0laRRACKgkI6AcQgICAgAIiiAEKDk1lc3NhZ2VPcHRpb25zEiYKF21lc3NhZ2Vfc2V0X3dpcmVfZm9ybWF0GAEgASgIOgVmYWxzZRJDChR1bmludGVycHJldGVkX29wdGlvbhjnByADKAsyJC5nb29nbGUucHJvdG9idWYuVW5pbnRlcnByZXRlZE9wdGlvbioJCOgHEICAgIACIoACCgxGaWVsZE9wdGlvbnMSMgoFY3R5cGUYASABKA4yIy5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zLkNUeXBlEg4KBnBhY2tlZBgCIAEoCBIZCgpkZXByZWNhdGVkGAMgASgIOgVmYWxzZRIcChRleHBlcmltZW50YWxfbWFwX2tleRgJIAEoCRJDChR1bmludGVycHJldGVkX29wdGlvbhjnByADKAsyJC5nb29nbGUucHJvdG9idWYuVW5pbnRlcnByZXRlZE9wdGlvbiIjCgVDVHlwZRIICgRDT1JEEAESEAoMU1RSSU5HX1BJRUNFEAIqCQjoBxCAgICAAiJdCgtFbnVtT3B0aW9ucxJDChR1bmludGVycHJldGVkX29wdGlvbhjnByADKAsyJC5nb29nbGUucHJvdG9idWYuVW5pbnRlcnByZXRlZE9wdGlvbioJCOgHEICAgIACImIKEEVudW1WYWx1ZU9wdGlvbnMSQwoUdW5pbnRlcnByZXRlZF9vcHRpb24Y5wcgAygLMiQuZ29vZ2xlLnByb3RvYnVmLlVuaW50ZXJwcmV0ZWRPcHRpb24qCQjoBxCAgICAAiJgCg5TZXJ2aWNlT3B0aW9ucxJDChR1bmludGVycHJldGVkX29wdGlvbhjnByADKAsyJC5nb29nbGUucHJvdG9idWYuVW5pbnRlcnByZXRlZE9wdGlvbioJCOgHEICAgIACIl8KDU1ldGhvZE9wdGlvbnMSQwoUdW5pbnRlcnByZXRlZF9vcHRpb24Y5wcgAygLMiQuZ29vZ2xlLnByb3RvYnVmLlVuaW50ZXJwcmV0ZWRPcHRpb24qCQjoBxCAgICAAiKFAgoTVW5pbnRlcnByZXRlZE9wdGlvbhI7CgRuYW1lGAIgAygLMi0uZ29vZ2xlLnByb3RvYnVmLlVuaW50ZXJwcmV0ZWRPcHRpb24uTmFtZVBhcnQSGAoQaWRlbnRpZmllcl92YWx1ZRgDIAEoCRIaChJwb3NpdGl2ZV9pbnRfdmFsdWUYBCABKAQSGgoSbmVnYXRpdmVfaW50X3ZhbHVlGAUgASgDEhQKDGRvdWJsZV92YWx1ZRgGIAEoARIUCgxzdHJpbmdfdmFsdWUYByABKAwaMwoITmFtZVBhcnQSEQoJbmFtZV9wYXJ0GAEgAigJEhQKDGlzX2V4dGVuc2lvbhgCIAIoCEIpChNjb20uZ29vZ2xlLnByb3RvYnVmQhBEZXNjcmlwdG9yUHJvdG9zSAE=");
		FileDescriptor.InternalDescriptorAssigner descriptorAssigner = delegate(FileDescriptor root)
		{
			descriptor = root;
			internal__static_google_protobuf_FileDescriptorSet__Descriptor = Descriptor.MessageTypes[0];
			internal__static_google_protobuf_FileDescriptorSet__FieldAccessorTable = new FieldAccessorTable<FileDescriptorSet, FileDescriptorSet.Builder>(internal__static_google_protobuf_FileDescriptorSet__Descriptor, new string[1] { "File" });
			internal__static_google_protobuf_FileDescriptorProto__Descriptor = Descriptor.MessageTypes[1];
			internal__static_google_protobuf_FileDescriptorProto__FieldAccessorTable = new FieldAccessorTable<FileDescriptorProto, FileDescriptorProto.Builder>(internal__static_google_protobuf_FileDescriptorProto__Descriptor, new string[8] { "Name", "Package", "Dependency", "MessageType", "EnumType", "Service", "Extension", "Options" });
			internal__static_google_protobuf_DescriptorProto__Descriptor = Descriptor.MessageTypes[2];
			internal__static_google_protobuf_DescriptorProto__FieldAccessorTable = new FieldAccessorTable<DescriptorProto, DescriptorProto.Builder>(internal__static_google_protobuf_DescriptorProto__Descriptor, new string[7] { "Name", "Field", "Extension", "NestedType", "EnumType", "ExtensionRange", "Options" });
			internal__static_google_protobuf_DescriptorProto_ExtensionRange__Descriptor = internal__static_google_protobuf_DescriptorProto__Descriptor.NestedTypes[0];
			internal__static_google_protobuf_DescriptorProto_ExtensionRange__FieldAccessorTable = new FieldAccessorTable<DescriptorProto.Types.ExtensionRange, DescriptorProto.Types.ExtensionRange.Builder>(internal__static_google_protobuf_DescriptorProto_ExtensionRange__Descriptor, new string[2] { "Start", "End" });
			internal__static_google_protobuf_FieldDescriptorProto__Descriptor = Descriptor.MessageTypes[3];
			internal__static_google_protobuf_FieldDescriptorProto__FieldAccessorTable = new FieldAccessorTable<FieldDescriptorProto, FieldDescriptorProto.Builder>(internal__static_google_protobuf_FieldDescriptorProto__Descriptor, new string[8] { "Name", "Number", "Label", "Type", "TypeName", "Extendee", "DefaultValue", "Options" });
			internal__static_google_protobuf_EnumDescriptorProto__Descriptor = Descriptor.MessageTypes[4];
			internal__static_google_protobuf_EnumDescriptorProto__FieldAccessorTable = new FieldAccessorTable<EnumDescriptorProto, EnumDescriptorProto.Builder>(internal__static_google_protobuf_EnumDescriptorProto__Descriptor, new string[3] { "Name", "Value", "Options" });
			internal__static_google_protobuf_EnumValueDescriptorProto__Descriptor = Descriptor.MessageTypes[5];
			internal__static_google_protobuf_EnumValueDescriptorProto__FieldAccessorTable = new FieldAccessorTable<EnumValueDescriptorProto, EnumValueDescriptorProto.Builder>(internal__static_google_protobuf_EnumValueDescriptorProto__Descriptor, new string[3] { "Name", "Number", "Options" });
			internal__static_google_protobuf_ServiceDescriptorProto__Descriptor = Descriptor.MessageTypes[6];
			internal__static_google_protobuf_ServiceDescriptorProto__FieldAccessorTable = new FieldAccessorTable<ServiceDescriptorProto, ServiceDescriptorProto.Builder>(internal__static_google_protobuf_ServiceDescriptorProto__Descriptor, new string[3] { "Name", "Method", "Options" });
			internal__static_google_protobuf_MethodDescriptorProto__Descriptor = Descriptor.MessageTypes[7];
			internal__static_google_protobuf_MethodDescriptorProto__FieldAccessorTable = new FieldAccessorTable<MethodDescriptorProto, MethodDescriptorProto.Builder>(internal__static_google_protobuf_MethodDescriptorProto__Descriptor, new string[4] { "Name", "InputType", "OutputType", "Options" });
			internal__static_google_protobuf_FileOptions__Descriptor = Descriptor.MessageTypes[8];
			internal__static_google_protobuf_FileOptions__FieldAccessorTable = new FieldAccessorTable<FileOptions, FileOptions.Builder>(internal__static_google_protobuf_FileOptions__Descriptor, new string[5] { "JavaPackage", "JavaOuterClassname", "JavaMultipleFiles", "OptimizeFor", "UninterpretedOption" });
			internal__static_google_protobuf_MessageOptions__Descriptor = Descriptor.MessageTypes[9];
			internal__static_google_protobuf_MessageOptions__FieldAccessorTable = new FieldAccessorTable<MessageOptions, MessageOptions.Builder>(internal__static_google_protobuf_MessageOptions__Descriptor, new string[2] { "MessageSetWireFormat", "UninterpretedOption" });
			internal__static_google_protobuf_FieldOptions__Descriptor = Descriptor.MessageTypes[10];
			internal__static_google_protobuf_FieldOptions__FieldAccessorTable = new FieldAccessorTable<FieldOptions, FieldOptions.Builder>(internal__static_google_protobuf_FieldOptions__Descriptor, new string[5] { "Ctype", "Packed", "Deprecated", "ExperimentalMapKey", "UninterpretedOption" });
			internal__static_google_protobuf_EnumOptions__Descriptor = Descriptor.MessageTypes[11];
			internal__static_google_protobuf_EnumOptions__FieldAccessorTable = new FieldAccessorTable<EnumOptions, EnumOptions.Builder>(internal__static_google_protobuf_EnumOptions__Descriptor, new string[1] { "UninterpretedOption" });
			internal__static_google_protobuf_EnumValueOptions__Descriptor = Descriptor.MessageTypes[12];
			internal__static_google_protobuf_EnumValueOptions__FieldAccessorTable = new FieldAccessorTable<EnumValueOptions, EnumValueOptions.Builder>(internal__static_google_protobuf_EnumValueOptions__Descriptor, new string[1] { "UninterpretedOption" });
			internal__static_google_protobuf_ServiceOptions__Descriptor = Descriptor.MessageTypes[13];
			internal__static_google_protobuf_ServiceOptions__FieldAccessorTable = new FieldAccessorTable<ServiceOptions, ServiceOptions.Builder>(internal__static_google_protobuf_ServiceOptions__Descriptor, new string[1] { "UninterpretedOption" });
			internal__static_google_protobuf_MethodOptions__Descriptor = Descriptor.MessageTypes[14];
			internal__static_google_protobuf_MethodOptions__FieldAccessorTable = new FieldAccessorTable<MethodOptions, MethodOptions.Builder>(internal__static_google_protobuf_MethodOptions__Descriptor, new string[1] { "UninterpretedOption" });
			internal__static_google_protobuf_UninterpretedOption__Descriptor = Descriptor.MessageTypes[15];
			internal__static_google_protobuf_UninterpretedOption__FieldAccessorTable = new FieldAccessorTable<UninterpretedOption, UninterpretedOption.Builder>(internal__static_google_protobuf_UninterpretedOption__Descriptor, new string[6] { "Name", "IdentifierValue", "PositiveIntValue", "NegativeIntValue", "DoubleValue", "StringValue" });
			internal__static_google_protobuf_UninterpretedOption_NamePart__Descriptor = internal__static_google_protobuf_UninterpretedOption__Descriptor.NestedTypes[0];
			internal__static_google_protobuf_UninterpretedOption_NamePart__FieldAccessorTable = new FieldAccessorTable<UninterpretedOption.Types.NamePart, UninterpretedOption.Types.NamePart.Builder>(internal__static_google_protobuf_UninterpretedOption_NamePart__Descriptor, new string[2] { "NamePart_", "IsExtension" });
			return (ExtensionRegistry)null;
		};
		FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData, new FileDescriptor[0], descriptorAssigner);
	}
}
