package com.sec.chaton.p057e;

import com.p137vk.sdk.api.VKApiConst;
import com.sec.chaton.buddy.p050a.EnumC1109f;
import com.sec.chaton.privateplugin.data.Spam;
import com.sec.common.util.C5052r;

/* compiled from: DatabaseHelper.java */
/* renamed from: com.sec.chaton.e.by */
/* loaded from: classes.dex */
public interface InterfaceC2279by {

    /* renamed from: a */
    public static final String f8167a = C5052r.m19199a("(", "SELECT ", "*", "FROM", "(", "SELECT ", "ifnull(", "b.", "buddy_name", ",", "''", ")", " AS ", "buddy_name", ",", "ifnull(", "b.", "buddy_no", ",", "a.", "message_sender", ")", " AS ", "buddy_no", ",", "ifnull(", "b.", "buddy_status_message", ",", "''", ")", " AS ", "buddy_status_message", ",", "ifnull(", "b.", "buddy_profile_status", ",", "''", ")", " AS ", "buddy_profile_status", ",", "a.", "message_content", ",", "a.", "message_content_type", ",", "a.", "message_download_uri", ",", "a.", "message_content_translated", ",", "a.", "message_from_lang", ",", "a.", "message_to_lang", ",", "a.", "message_is_spoken", ",", "a.", "message_formatted", ",", "a.", "_id", ",", "a.", "message_inbox_no", ",", "a.", "message_read_status", ",", "a.", "message_sender", ",", "a.", "message_sever_id", ",", "a.", "message_session_id", ",", "a.", "message_time", ",", "a.", "message_translated", ",", "a.", "message_stored_ext", ",", "a.", "message_is_failed", ",", "a.", "message_is_file_upload", ",", "a.", "message_type", " FROM ", VKApiConst.MESSAGE, " a", " LEFT OUTER JOIN ", "(", "SELECT ", "buddy_no", ",", "buddy_name", ",", "buddy_status_message", ",", "buddy_profile_status", " FROM ", "buddy", " UNION ALL ", "SELECT ", "participants_buddy_no", " AS ", "buddy_no", ",", "MAX", "(", "participants_buddy_name", ")", " AS ", "buddy_name", ",", "''", " AS ", "buddy_status_message", ",", "''", " AS ", "buddy_profile_status", " FROM ", "participant", " WHERE ", "participants_buddy_no", " NOT IN ", "(SELECT ", "buddy_no", " FROM ", "buddy", ")", " GROUP BY ", "participants_buddy_no", ") b", " ON ", "a.", "message_sender", " = ", "b.", "buddy_no", ") c", " LEFT OUTER JOIN ", "(", "SELECT ", "b.", "participants_inbox_no", " AS ", "inbox_no", " FROM ", "(", "SELECT ", "participants_buddy_no", ",", "participants_inbox_no", " FROM ", "participant", " WHERE ", "participants_inbox_no", " IN ", "(SELECT ", "inbox_no", " FROM ", "inbox", " WHERE ", "inbox_chat_type", " = ", String.valueOf(EnumC2300t.ONETOONE.m10210a()), ")", ") b", " LEFT OUTER JOIN ", "buddy", " a", " ON ", "b.", "participants_buddy_no", " = ", "a.", "buddy_no", ") d", " ON ", "c.", "message_inbox_no", " = ", "d.", "inbox_no", ")");

    /* renamed from: b */
    public static final String f8168b = C5052r.m19199a("SELECT ", "*", " FROM", "(", "SELECT ", "ifnull(c.is_buddy,'N') AS is_buddy,", "ifnull(", "c.", "buddy_name", ",", "''", ")", " AS ", "buddy_name", ",", "ifnull(", "c.", "buddy_no", ",", "a.", "message_sender", ")", " AS ", "buddy_no", ",", "ifnull(", "c.", "buddy_status_message", ",", "''", ")", " AS ", "buddy_status_message", ",", "ifnull(", "c.", "buddy_show_phone_number", ",", String.valueOf(0), ")", " AS ", "buddy_show_phone_number", ",", "ifnull(", "c.", "buddy_profile_status", ",", "''", ")", " AS ", "buddy_profile_status", ",", "a.", "message_content", ",", "a.", "message_content_type", ",", "a.", "message_content_translated", ",", "a.", "message_from_lang", ",", "a.", "message_to_lang", ",", "a.", "message_is_spoken", ",", "a.", "message_download_uri", ",", "a.", "message_formatted", ",", "a.", "_id", ",", "a.", "message_inbox_no", ",", "a.", "message_read_status", ",", "a.", "message_sender", ",", "a.", "message_sever_id", ",", "a.", "message_session_id", ",", "a.", "message_time", ",", "a.", "message_translated", ",", "a.", "message_stored_ext", ",", "a.", "message_is_failed", ",", "a.", "message_is_file_upload", ",", "a.", "message_type", ",", "a.", "message_status", " FROM ", "( ", "SELECT ", "*", " FROM ", VKApiConst.MESSAGE, " WHERE ", "message_inbox_no", " = ?", " AND (", "message_is_truncated", " = 'N'", " OR ", "message_content_type", " = ", String.valueOf(EnumC2214ab.TEXT.m10076a()), ")", " AND ", "message_content_type", " != ", Integer.valueOf(EnumC2214ab.LIVECONTENTS.m10076a()), " ORDER BY ", "message_is_failed", " DESC , ", "message_time", " DESC , ", "_id", " DESC", " LIMIT ?", " ) a", " LEFT OUTER JOIN ", "(", "SELECT ", "p.", "participants_buddy_no", " AS ", "buddy_no", ", ", "ifnull(", "b.", "buddy_name", ", ", "p.", "participants_buddy_name", ") AS ", "buddy_name", ", ", "b.", "buddy_status_message", ", ", "b.", "buddy_show_phone_number", ", ", "b.", "buddy_profile_status", ", ", "ifnull(is_buddy,'N') AS is_buddy", " FROM ", "participant", " p", " LEFT OUTER JOIN ", "(", "SELECT ", "buddy_no", ",", "buddy_name", ",", "buddy_status_message", ",", "buddy_show_phone_number", ",", "buddy_profile_status", ", ", "'Y' AS is_buddy", " FROM ", "buddy", " UNION ALL ", "SELECT ", "buddy_no", ", ", "buddy_original_name", " AS ", "buddy_name", ", ", "''", " AS ", "buddy_status_message", ",", "''", " AS ", "buddy_show_phone_number", ",", "''", " AS ", "buddy_profile_status", ", ", "'N' AS is_buddy", " FROM ", "unknownbuddy", ")", " b", " ON ", "p.", "participants_buddy_no", " = ", "b.", "buddy_no", " WHERE ", "p.", "participants_inbox_no", " = ?", " OR ", "p.", "participants_inbox_no", " = ''", " GROUP BY ", "buddy_no", ") c", " ON ", "a.", "message_sender", " = ", "c.", "buddy_no", ") d", " ORDER BY ", "message_is_failed", " , ", "message_time", " , ", "_id");

    /* renamed from: c */
    public static final String f8169c = "SELECT * FROM(SELECT ifnull(c.buddy_name,'') AS buddy_name,ifnull(c.buddy_no,a.message_sender) AS buddy_no,ifnull(c.buddy_status_message,'') AS buddy_status_message,a.message_content,a.message_content_translated,a.message_from_lang,a.message_to_lang,a.message_is_spoken,a.message_content_type,a.message_download_uri,a.message_formatted,a._id,a.message_inbox_no,a.message_read_status,a.message_sender,a.message_sever_id,a.message_session_id,a.message_time,a.message_translated,a.message_stored_ext,a.message_is_failed,a.message_is_file_upload,a.message_type,a.message_is_truncated FROM ( SELECT * FROM message WHERE message_inbox_no = ? AND message_type = '" + Integer.toString(2) + "' ORDER BY message_is_failed DESC , message_time DESC , _id DESC LIMIT ? ) a LEFT OUTER JOIN (SELECT p.participants_buddy_no AS buddy_no, ifnull(b.buddy_name, p.participants_buddy_name) AS buddy_name, b.buddy_status_message FROM participant p LEFT OUTER JOIN ( SELECT buddy_no, buddy_status_message, buddy_name FROM buddy UNION ALL SELECT buddy_no AS buddy_no, '' AS buddy_status_message, buddy_original_name AS buddy_name FROM unknownbuddy UNION ALL SELECT buddy_no AS buddy_no, msgstatus AS buddy_status_message, buddy_name AS buddy_name FROM specialbuddy ) b ON p.participants_buddy_no = b.buddy_no WHERE p.participants_inbox_no = ? OR p.participants_inbox_no = '' GROUP BY buddy_no) c ON a.message_sender = c.buddy_no) d";

    /* renamed from: d */
    public static final String f8170d = "SELECT M._id AS _id, M.message_sever_id AS message_sever_id, M.message_inbox_no AS message_inbox_no, M.message_content_type AS message_content_type, M.message_time AS message_time, M.message_content AS message_content, M.message_type AS message_type, M.message_download_uri, M.message_formatted, M.message_is_failed AS message_is_failed, M.message_is_file_upload, M.message_content_translated, I.inbox_no AS inbox_no, I.inbox_chat_type AS inbox_chat_type, I.inbox_server_ip AS inbox_server_ip, I.inbox_server_port AS inbox_server_port, I.inbox_participants AS inbox_participants, I.inbox_session_id AS inbox_session_id, I.inbox_valid AS inbox_valid, I.inbox_room_type AS inbox_room_type, I.lasst_session_merge_time AS lasst_session_merge_time FROM message AS M INNER JOIN inbox AS I ON M.message_inbox_no = I.inbox_no WHERE M.message_sender = ?  AND ( M.message_type = 0 OR M.message_type = -1 OR M.message_type = 6 ) AND (NOT (M.message_content = " + EnumC2214ab.HUGEFILE.m10076a() + " AND M.message_is_file_upload = 0))";

    /* renamed from: e */
    public static final String f8171e = "SELECT M._id, M.message_sever_id, M.message_inbox_no, M.message_time, M.message_sender, M.message_is_read, M.message_is_ack FROM message AS M WHERE M.message_inbox_no IN (SELECT I.inbox_no FROM inbox AS I WHERE I.inbox_room_type = " + EnumC2301u.LIVE.m10212a() + ")  AND M.message_type = 2 AND M.message_content_type != " + EnumC2214ab.LIVECONTENTS.m10076a() + " AND M.message_content_type != " + EnumC2214ab.SYSTEM.m10076a() + " AND M.message_content_type != " + EnumC2214ab.UNDEFINED.m10076a() + " AND ( M.message_is_read = " + EnumC2215ac.READ_LOCAL.m10080a() + " OR  M.message_is_ack = " + EnumC2213aa.ACK_NOT_YET.m10069a() + " ) ORDER BY M.message_time";

    /* renamed from: f */
    public static final String f8172f = C5052r.m19199a("(", "SELECT ", "ifnull(", "b.", "buddy_no", ",", "c.", "participants_buddy_no", ")", " AS ", "buddy_no", ",", "ifnull(", "b.", "buddy_status_message", ",", "''", ")", " AS ", "buddy_status_message", ",", "ifnull(", "b.", "buddy_name", ",", "c.", "participants_buddy_name", ")", " AS ", "buddy_name", ",", "c.", "participants_inbox_no", " AS ", "participants_inbox_no", ",", "c.", "participants_buddy_no", " AS ", "participants_buddy_no", ",", "c.", "rowid", " AS ", "rowid", ",", "ifnull(", "c.", "participants_country_code", ",'') AS ", "participants_country_code", ",", "ifnull(", "c.", "participants_is_auth", ",'') AS ", "participants_is_auth", ",", "ifnull(", "c.", "participants_status", ",0) AS ", "participants_status", ",", "ifnull(", "b.", "buddy_account_info", ",", "c.", "participants_account_info", ")", " AS ", "buddy_account_info", ",", "ifnull(", "c.", "participants_sms_address", ",'') AS ", "participants_sms_address", ",", "ifnull(", "c.", "participants_read_time", ",0) AS ", "participants_read_time", ",", "ifnull(", "c.", "participants_user_type", ", ", EnumC1109f.NONE.m7095a(), ") AS ", "participants_user_type", ",", "ifnull(", "b.", "buddy_extra_info", ",'') AS ", "buddy_extra_info", " FROM ", "(", "SELECT ", "ifnull(", "participants_buddy_name", ",'') AS ", "participants_buddy_name", ",", "participants_buddy_no", ",", "participants_inbox_no", ",", "rowid", ",", "ifnull(", "participants_country_code", ",'') AS ", "participants_country_code", ",", "ifnull(", "participants_is_auth", ",'') AS ", "participants_is_auth", ",", "ifnull(", "participants_status", ",0) AS ", "participants_status", ",", "ifnull(", "participants_sms_address", ",'') AS ", "participants_sms_address", ",", "ifnull(", "participants_read_time", ",0) AS ", "participants_read_time", ",", "participants_user_type", ",", "participants_account_info", " FROM ", "participant", ") c", " LEFT OUTER JOIN ", "( ", "SELECT ", "buddy_no", ", ", "buddy_status_message", ", ", "buddy_name", ", ", "buddy_account_info", ", ", "buddy_extra_info", " FROM ", "buddy", " UNION ALL ", "SELECT ", "buddy_no", " AS ", "buddy_no", ", ", "'' AS ", "buddy_status_message", ", ", "buddy_original_name", " AS ", "buddy_name", ", ", Spam.ACTIVITY_CANCEL, " AS ", "buddy_account_info", ", ", "'' AS ", "buddy_extra_info", " FROM unknownbuddy", " UNION ALL ", "SELECT ", "buddy_no", " AS ", "buddy_no", ", ", "msgstatus", " AS ", "buddy_status_message", ", ", "buddy_name", " AS ", "buddy_name", ", ", Spam.ACTIVITY_CANCEL, " AS ", "buddy_account_info", ", ", "'' AS ", "buddy_extra_info", " FROM ", "specialbuddy", " )", " b", " ON ", "c.", "participants_buddy_no", " = ", "b.", "buddy_no", ")");

    /* renamed from: g */
    public static final String f8173g = C5052r.m19199a("(", "SELECT ", "a.", "buddy_no", ",", "a.", "buddy_name", ",", "b.", "participants_inbox_no", " FROM ", "(", "SELECT ", "buddy_no", ",", "buddy_name", " FROM ", "buddy", " UNION ALL ", "SELECT ", "buddy_no", " AS ", "buddy_no", ",", "buddy_name", " AS ", "buddy_name", " FROM ", "specialbuddy", " UNION ALL ", "SELECT ", "participants_buddy_no", " AS ", "buddy_no", ",", "MAX", "(", "participants_buddy_name", ")", " AS ", "buddy_name", " FROM ", "participant", " WHERE ", "participants_buddy_no", " NOT IN ", "( ", "SELECT ", "buddy_no", " FROM ", "buddy", " UNION ALL ", "SELECT ", "buddy_no", " AS ", "buddy_name", " FROM ", "specialbuddy", ")", " GROUP BY ", "participants_buddy_no", ") a", " LEFT OUTER JOIN ", "participant", " b", " ON ", "b.", "participants_buddy_no", "=", " a.", "buddy_no", ")");

    /* renamed from: h */
    public static final String f8174h = C5052r.m19199a("(", "SELECT ifnull(b.", "_id", ",'1') AS ", "_id", ", p.", "participants_inbox_no", ",p.", "participants_buddy_no", " AS ", "buddy_no", ",", "ifnull(b.", "buddy_name", ",p.", "participants_buddy_no", ") AS ", "buddy_name", ",ifnull(b.", "buddy_status_message", ",'') AS ", "buddy_status_message", ",ifnull(b.is_buddy,'N') AS is_buddy, ifnull(b.", "buddy_contact_buddy", ",2) AS ", "buddy_contact_buddy", ", p.", "participants_sms_address", " FROM ", "participant", " p LEFT OUTER JOIN (", " SELECT ", "_id", ",", "buddy_no", ",", "buddy_name", ",'Y' AS is_buddy,", "buddy_status_message", ",", "buddy_contact_buddy", " FROM ", "buddy", ") b ON p.", "participants_buddy_no", " = b.", "buddy_no", ")");

    /* renamed from: i */
    public static final String f8175i = C5052r.m19199a("(", "SELECT ifnull(b.", "_id", ",'1') AS ", "_id", ", ", "p.", "participants_inbox_no", ",", "p.", "participants_buddy_no", " AS ", "buddy_no", ", ", "ifnull(b.", "buddy_name", ",p.", "participants_buddy_name", ") AS ", "buddy_name", ", ", "ifnull(b.", "buddy_status_message", ",'') AS ", "buddy_status_message", ", ", "ifnull(b.is_buddy,'N') AS is_buddy", ", ", "ifnull(p.", "participants_user_type", ", ", EnumC1109f.NONE.m7095a(), ") AS ", "participants_user_type", ", ", "u.", "buddy_original_name", ", ", "u.", "blocked", ", ", "u.", "hided", " FROM ", "participant", " p ", " LEFT OUTER JOIN ", "(", " SELECT ", "_id", ",", "buddy_no", ",", "buddy_name", ", ", "'Y' AS is_buddy,", "buddy_status_message", " FROM ", "buddy", " UNION ALL ", " SELECT ", "_id", ", ", "buddy_no", " AS ", "buddy_no", ", ", "buddy_original_name", " AS ", "buddy_name", ", ", "'N' AS is_buddy", ", ", "'' AS ", "buddy_status_message", " FROM ", "unknownbuddy", ") b ", "ON p.", "participants_buddy_no", " = b.", "buddy_no", " LEFT OUTER JOIN ", "unknownbuddy", " u ON p.", "participants_buddy_no", " = u.", "buddy_no", ")");

    /* renamed from: j */
    public static final String f8176j = "(SELECT ifnull (s._id, '1') AS _id, p.participants_inbox_no, p.participants_buddy_no AS buddy_no, ifnull (s.buddy_name, p.participants_buddy_name) AS buddy_name, ifnull (s.description, '') AS buddy_status_message, ifnull (s.is_buddy, 'N') AS is_buddy, ifnull (p.participants_user_type, " + EnumC1109f.NONE.m7095a() + ") AS participants_user_type FROM participant p  LEFT OUTER JOIN ( SELECT _id, buddy_no, buddy_name, 'Y' AS is_buddy, description FROM specialbuddy) s ON p.participants_buddy_no = s.buddy_no)";

    /* renamed from: k */
    public static final String f8177k = C5052r.m19199a("SELECT ", "message_total_count", ", ", "ifnull(", "message_sent_count", ", 0) AS ", "message_sent_count", ", ", "ifnull(", "a.", "message_inbox_no", ", ", "b.", "message_inbox_no", ") AS ", "message_inbox_no", " FROM ", "( ", "( ", "SELECT count(*) AS ", "message_total_count", ", ", "message_inbox_no", " FROM ", VKApiConst.MESSAGE, " WHERE ", "message_inbox_no", " = ? AND ", "message_content_type", " != ", Integer.toString(EnumC2214ab.SYSTEM.m10076a()), " ) a", " LEFT OUTER JOIN ", "( ", "SELECT count(*) AS ", "message_sent_count", ", ", "message_inbox_no", " FROM ", VKApiConst.MESSAGE, " WHERE ", "message_inbox_no", " = ? AND ", "message_content_type", " != ", Integer.toString(EnumC2214ab.SYSTEM.m10076a()), " AND ", "message_sender", " = ? ", " ) b", " ON a.", "message_inbox_no", " = b.", "message_inbox_no", " )");

    /* renamed from: l */
    public static final String f8178l = " SELECT * FROM(SELECT ifnull(c.buddy_name,'') AS buddy_name,ifnull(c.buddy_no,a.message_sender) AS buddy_no,ifnull(c.buddy_status_message,'') AS buddy_status_message,ifnull(c.buddy_show_phone_number," + String.valueOf(0) + ") AS buddy_show_phone_number,ifnull(c.buddy_profile_status,'') AS buddy_profile_status,a.message_content,a.message_content_type,a.message_download_uri,a.message_formatted,a._id,a.message_inbox_no,a.message_read_status,a.message_sender,a.message_sever_id,a.message_session_id,a.message_time,a.message_translated,a.message_stored_ext,a.message_is_failed,a.message_is_file_upload,a.message_type FROM ( SELECT * FROM " + VKApiConst.MESSAGE + " WHERE message_inbox_no = ? AND message_is_truncated = 'N' AND ( message_content_type = " + String.valueOf(EnumC2214ab.IMAGE.m10076a()) + " OR message_content_type = " + String.valueOf(EnumC2214ab.VIDEO.m10076a()) + " OR message_content_type = " + String.valueOf(EnumC2214ab.AMS.m10076a()) + ") ORDER BY message_is_failed DESC , message_time DESC , _id DESC ) a LEFT OUTER JOIN (SELECT p.participants_buddy_no AS buddy_no, ifnull(b.buddy_name, p.participants_buddy_name) AS buddy_name, b.buddy_status_message, b.buddy_show_phone_number, b.buddy_profile_status FROM participant p LEFT OUTER JOIN buddy b ON p.participants_buddy_no = b.buddy_no WHERE p.participants_inbox_no = ? OR p.participants_inbox_no = '' GROUP BY buddy_no) c ON a.message_sender = c.buddy_no) d ORDER BY message_is_failed , message_time , _id";

    /* renamed from: m */
    public static final String f8179m = "UPDATE message SET message_content_type = " + EnumC2214ab.LIVECONTENTS.m10076a() + " WHERE message_sever_id IN  ( SELECT message_sever_id FROM  ( SELECT message_sever_id, message_sender FROM " + VKApiConst.MESSAGE + " LEFT OUTER JOIN specialbuddy WHERE message_sender = buddy_no )  ) ";

    /* renamed from: n */
    public static final String f8180n = " _id IN  ( SELECT m._id FROM message m  INNER JOIN inbox i  ON i.inbox_no = m.message_inbox_no WHERE m.message_type = 0 AND ( i.inbox_room_type = " + EnumC2301u.LIVE.m10212a() + " OR ( m.message_content_type = " + EnumC2214ab.HUGEFILE.m10076a() + " AND m.message_is_file_upload != 1 )))";

    /* renamed from: o */
    public static final String f8181o = " _id IN  ( SELECT m._id FROM message m  INNER JOIN inbox i  ON i.inbox_no = m.message_inbox_no WHERE m.message_type = 0 AND i.inbox_room_type != " + EnumC2301u.LIVE.m10212a() + " AND (( m.message_content_type != " + EnumC2214ab.HUGEFILE.m10076a() + ") OR (m.message_content_type = " + EnumC2214ab.HUGEFILE.m10076a() + " AND m.message_is_file_upload = 1)))";
}
