internal enum VCAL_PROFILE_FEATURES
{
	VCAL_TAG_NONE,
	VCAL_TAG_BEGIN,
	VCAL_TAG_END,
	VCAL_TAG_VERSION,
	VCAL_TAG_SUMMARY,
	VCAL_TAG_DTSTART,
	VCAL_TAG_DTEND,
	VCAL_TAG_DESCRIPTION,
	VCAL_TAG_LOCATION,
	VCAL_TAG_ATTACH,
	VCAL_TAG_DTSTART_MS,
	VCAL_TAG_DTEND_MS,
	VCAL_TAG_ATTACH_MS,
	VCAL_TAG_MAX
}
