internal enum VCARDTAGNUMBER
{
	VCARD_TAG_NONE,
	VCARD_TAG_BEGIN,
	VCARD_TAG_END,
	VCARD_TAG_VERSION,
	VCARD_TAG_FN,
	VCARD_TAG_N,
	VCARD_TAG_TEL,
	VCARD_TAG_EMAIL,
	VCARD_TAG_NOTE,
	VCARD_TAG_XMS_NOTE,
	VCARD_TAG_MAX
}
