internal enum VITEMS
{
	VITEM_FULL_NAME_LEN = 300,
	VITEM_NAME_LEN = 300,
	VITEM_CODE_MAX = 2,
	VITEM_GROUP_CNT = 100,
	VITEM_NUMBER_CNT = 12,
	VITEM_EMAIL_CNT = 6,
	VITEM_ADDR_CNT = 4,
	VITEM_URL_CNT = 2,
	VITEM_NOT_EXIST = -1,
	VITEM_NUMBER_LEN = 300,
	VITEM_EMAIL_LEN = 300,
	VITEM_MEMO_LEN = 300,
	DECODING_MAX_LENGTH = 3400,
	VITEM_SUMMARY_LEN = 300,
	VITEM_LOCATION_LEN = 300,
	VITEM_DESCRIPTION_LEN = 300
}
