public enum VITEMCHARACTERSET
{
	VITEM_CHARSET_NONE,
	VITEM_CHARSET_ASCII,
	VITEM_CHARSET_LATIN1,
	VITEM_CHARSET_UTF7,
	VITEM_CHARSET_UTF8,
	VITEM_CHARSET_UTF8_NO_ESC,
	VITEM_CHARSET_UCS2,
	VITEM_CHARSET_SHIFT_JIS
}
