package org.jboss.netty.util.internal.jzlib;

import com.sec.amsoma.AMSLibs;
import org.jboss.netty.handler.codec.http.websocket.WebSocketFrameDecoder;

/* loaded from: classes.dex */
final class Tree {
    short[] dyn_tree;
    int max_code;
    StaticTree stat_desc;
    static final int[] extra_lbits = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0};
    static final int[] extra_dbits = {0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13};
    static final int[] extra_blbits = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 7};
    static final byte[] bl_order = {AMSLibs.ENUM_VIP_AMS_ERROR_ENCODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_LOAD_JPEGTORAW, AMSLibs.ENUM_VIP_AMS_ERROR_CONVERT_IMAGEBUFFER, 0, 8, 7, 9, 6, 10, 5, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, 4, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, 3, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, 2, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, 1, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL};
    static final byte[] _dist_code = {0, 1, 2, 3, 4, 4, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, 0, 0, AMSLibs.ENUM_VIP_AMS_ERROR_ENCODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_LOAD_JPEGTORAW, AMSLibs.ENUM_VIP_AMS_ERROR_CONVERT_IMAGEBUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_CONVERT_IMAGEBUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_BUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_BUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_DRAWING_DATA};
    static final byte[] _length_code = {0, 1, 2, 3, 4, 5, 6, 7, 8, 8, 9, 9, 10, 10, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_TEXT_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_STAMP_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_DIAGRAM_OBJECT_NUM_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_TRANSMIT_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_USERIMAGE_ID_FULL, AMSLibs.ENUM_VIP_AMS_ERROR_ENCODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_ENCODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_ENCODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_ENCODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_ENCODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_ENCODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_ENCODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_ENCODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_LOAD_JPEGTORAW, AMSLibs.ENUM_VIP_AMS_ERROR_LOAD_JPEGTORAW, AMSLibs.ENUM_VIP_AMS_ERROR_LOAD_JPEGTORAW, AMSLibs.ENUM_VIP_AMS_ERROR_LOAD_JPEGTORAW, AMSLibs.ENUM_VIP_AMS_ERROR_LOAD_JPEGTORAW, AMSLibs.ENUM_VIP_AMS_ERROR_LOAD_JPEGTORAW, AMSLibs.ENUM_VIP_AMS_ERROR_LOAD_JPEGTORAW, AMSLibs.ENUM_VIP_AMS_ERROR_LOAD_JPEGTORAW, AMSLibs.ENUM_VIP_AMS_ERROR_CONVERT_IMAGEBUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_CONVERT_IMAGEBUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_CONVERT_IMAGEBUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_CONVERT_IMAGEBUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_CONVERT_IMAGEBUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_CONVERT_IMAGEBUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_CONVERT_IMAGEBUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_CONVERT_IMAGEBUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_BUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_BUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_BUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_BUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_BUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_BUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_BUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_BUFFER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_HEADER, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_DATA, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_EXIF, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_DECODE_IMAGE, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_SAVE_FLASH, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_UNDEFINED, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_INVALID_FILEINFO, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_PROPERTY_SETTING, AMSLibs.ENUM_VIP_AMS_ERROR_OBJECT_START_SETTING};
    static final int[] base_length = {0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 16, 20, 24, 28, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 0};
    static final int[] base_dist = {0, 1, 2, 3, 4, 6, 8, 12, 16, 24, 32, 48, 64, 96, 128, 192, 256, 384, 512, 768, 1024, 1536, 2048, 3072, 4096, 6144, 8192, 12288, WebSocketFrameDecoder.DEFAULT_MAX_FRAME_SIZE, 24576};

    Tree() {
    }

    static int d_code(int i) {
        return i < 256 ? _dist_code[i] : _dist_code[(i >>> 7) + 256];
    }

    /* JADX WARN: Multi-variable type inference failed */
    private void gen_bitlen(Deflate deflate) {
        short[] sArr = this.dyn_tree;
        short[] sArr2 = this.stat_desc.static_tree;
        int[] iArr = this.stat_desc.extra_bits;
        int i = this.stat_desc.extra_base;
        int i2 = this.stat_desc.max_length;
        for (int i3 = 0; i3 <= 15; i3++) {
            deflate.bl_count[i3] = 0;
        }
        sArr[(deflate.heap[deflate.heap_max] * 2) + 1] = 0;
        int i4 = deflate.heap_max + 1;
        int i5 = 0;
        while (i4 < 573) {
            int i6 = deflate.heap[i4];
            int i7 = sArr[(sArr[(i6 * 2) + 1] * 2) + 1] + 1;
            if (i7 > i2) {
                i5++;
                i7 = i2;
            }
            sArr[(i6 * 2) + 1] = (short) i7;
            if (i6 <= this.max_code) {
                short[] sArr3 = deflate.bl_count;
                sArr3[i7] = (short) (sArr3[i7] + 1);
                int i8 = i6 >= i ? iArr[i6 - i] : 0;
                short s = sArr[i6 * 2];
                deflate.opt_len = ((i7 + i8) * s) + deflate.opt_len;
                if (sArr2 != null) {
                    deflate.static_len += (i8 + sArr2[(i6 * 2) + 1]) * s;
                }
            }
            i4++;
        }
        if (i5 != 0) {
            do {
                int i9 = i2 - 1;
                while (deflate.bl_count[i9] == 0) {
                    i9--;
                }
                deflate.bl_count[i9] = (short) (r3[i9] - 1);
                short[] sArr4 = deflate.bl_count;
                int i10 = i9 + 1;
                sArr4[i10] = (short) (sArr4[i10] + 2);
                deflate.bl_count[i2] = (short) (r1[i2] - 1);
                i5 -= 2;
            } while (i5 > 0);
            int i11 = i4;
            while (i2 != 0) {
                short s2 = deflate.bl_count[i2];
                while (s2 != 0) {
                    i11--;
                    int i12 = deflate.heap[i11];
                    if (i12 <= this.max_code) {
                        if (sArr[(i12 * 2) + 1] != i2) {
                            deflate.opt_len = (int) (deflate.opt_len + ((i2 - sArr[(i12 * 2) + 1]) * sArr[i12 * 2]));
                            sArr[(i12 * 2) + 1] = (short) i2;
                        }
                        s2--;
                    }
                }
                i2--;
            }
        }
    }

    void build_tree(Deflate deflate) {
        int i;
        short[] sArr = this.dyn_tree;
        short[] sArr2 = this.stat_desc.static_tree;
        int i2 = this.stat_desc.elems;
        int i3 = -1;
        deflate.heap_len = 0;
        deflate.heap_max = 573;
        for (int i4 = 0; i4 < i2; i4++) {
            if (sArr[i4 * 2] != 0) {
                int[] iArr = deflate.heap;
                int i5 = deflate.heap_len + 1;
                deflate.heap_len = i5;
                iArr[i5] = i4;
                deflate.depth[i4] = 0;
                i3 = i4;
            } else {
                sArr[(i4 * 2) + 1] = 0;
            }
        }
        while (deflate.heap_len < 2) {
            int[] iArr2 = deflate.heap;
            int i6 = deflate.heap_len + 1;
            deflate.heap_len = i6;
            if (i3 < 2) {
                i3++;
                i = i3;
            } else {
                i = 0;
            }
            iArr2[i6] = i;
            sArr[i * 2] = 1;
            deflate.depth[i] = 0;
            deflate.opt_len--;
            if (sArr2 != null) {
                deflate.static_len -= sArr2[(i * 2) + 1];
            }
        }
        this.max_code = i3;
        for (int i7 = deflate.heap_len / 2; i7 >= 1; i7--) {
            deflate.pqdownheap(sArr, i7);
        }
        int i8 = i2;
        while (true) {
            int i9 = deflate.heap[1];
            int[] iArr3 = deflate.heap;
            int[] iArr4 = deflate.heap;
            int i10 = deflate.heap_len;
            deflate.heap_len = i10 - 1;
            iArr3[1] = iArr4[i10];
            deflate.pqdownheap(sArr, 1);
            int i11 = deflate.heap[1];
            int[] iArr5 = deflate.heap;
            int i12 = deflate.heap_max - 1;
            deflate.heap_max = i12;
            iArr5[i12] = i9;
            int[] iArr6 = deflate.heap;
            int i13 = deflate.heap_max - 1;
            deflate.heap_max = i13;
            iArr6[i13] = i11;
            sArr[i8 * 2] = (short) (sArr[i9 * 2] + sArr[i11 * 2]);
            deflate.depth[i8] = (byte) (Math.max((int) deflate.depth[i9], (int) deflate.depth[i11]) + 1);
            short s = (short) i8;
            sArr[(i11 * 2) + 1] = s;
            sArr[(i9 * 2) + 1] = s;
            int i14 = i8 + 1;
            deflate.heap[1] = i8;
            deflate.pqdownheap(sArr, 1);
            if (deflate.heap_len < 2) {
                int[] iArr7 = deflate.heap;
                int i15 = deflate.heap_max - 1;
                deflate.heap_max = i15;
                iArr7[i15] = deflate.heap[1];
                gen_bitlen(deflate);
                gen_codes(sArr, i3, deflate.bl_count);
                return;
            }
            i8 = i14;
        }
    }

    private static void gen_codes(short[] sArr, int i, short[] sArr2) {
        short[] sArr3 = new short[16];
        short s = 0;
        for (int i2 = 1; i2 <= 15; i2++) {
            s = (short) ((s + sArr2[i2 - 1]) << 1);
            sArr3[i2] = s;
        }
        for (int i3 = 0; i3 <= i; i3++) {
            short s2 = sArr[(i3 * 2) + 1];
            if (s2 != 0) {
                short s3 = sArr3[s2];
                sArr3[s2] = (short) (s3 + 1);
                sArr[i3 * 2] = (short) bi_reverse(s3, s2);
            }
        }
    }

    private static int bi_reverse(int i, int i2) {
        int i3 = 0;
        do {
            int i4 = i3 | (i & 1);
            i >>>= 1;
            i3 = i4 << 1;
            i2--;
        } while (i2 > 0);
        return i3 >>> 1;
    }
}
