using System;
using Google.ProtocolBuffers;
using Google.ProtocolBuffers.Descriptors;
using Google.ProtocolBuffers.FieldAccess;

namespace com.sec.ssm.common;

public static class SSMGPB
{
	internal static MessageDescriptor internal__static_com_sec_ssm_common_MemberTransition__Descriptor;

	internal static FieldAccessorTable<MemberTransition, MemberTransition.Builder> internal__static_com_sec_ssm_common_MemberTransition__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_SessionMergeResult__Descriptor;

	internal static FieldAccessorTable<SessionMergeResult, SessionMergeResult.Builder> internal__static_com_sec_ssm_common_SessionMergeResult__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_Result__Descriptor;

	internal static FieldAccessorTable<Result, Result.Builder> internal__static_com_sec_ssm_common_Result__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_Nickname__Descriptor;

	internal static FieldAccessorTable<Nickname, Nickname.Builder> internal__static_com_sec_ssm_common_Nickname__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_InboxMessage__Descriptor;

	internal static FieldAccessorTable<InboxMessage, InboxMessage.Builder> internal__static_com_sec_ssm_common_InboxMessage__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_DeliveryChatReplyItem__Descriptor;

	internal static FieldAccessorTable<DeliveryChatReplyItem, DeliveryChatReplyItem.Builder> internal__static_com_sec_ssm_common_DeliveryChatReplyItem__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_AnswerbackItem__Descriptor;

	internal static FieldAccessorTable<AnswerbackItem, AnswerbackItem.Builder> internal__static_com_sec_ssm_common_AnswerbackItem__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_ServerInfo__Descriptor;

	internal static FieldAccessorTable<ServerInfo, ServerInfo.Builder> internal__static_com_sec_ssm_common_ServerInfo__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_ChangeMemberList__Descriptor;

	internal static FieldAccessorTable<ChangeMemberList, ChangeMemberList.Builder> internal__static_com_sec_ssm_common_ChangeMemberList__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_EndParam__Descriptor;

	internal static FieldAccessorTable<EndParam, EndParam.Builder> internal__static_com_sec_ssm_common_EndParam__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_InitChatRequest__Descriptor;

	internal static FieldAccessorTable<InitChatRequest, InitChatRequest.Builder> internal__static_com_sec_ssm_common_InitChatRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_InitChatReply__Descriptor;

	internal static FieldAccessorTable<InitChatReply, InitChatReply.Builder> internal__static_com_sec_ssm_common_InitChatReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_AllowChatRequest__Descriptor;

	internal static FieldAccessorTable<AllowChatRequest, AllowChatRequest.Builder> internal__static_com_sec_ssm_common_AllowChatRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_AllowChatReply__Descriptor;

	internal static FieldAccessorTable<AllowChatReply, AllowChatReply.Builder> internal__static_com_sec_ssm_common_AllowChatReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_ChatRequest__Descriptor;

	internal static FieldAccessorTable<ChatRequest, ChatRequest.Builder> internal__static_com_sec_ssm_common_ChatRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_ChatReply__Descriptor;

	internal static FieldAccessorTable<ChatReply, ChatReply.Builder> internal__static_com_sec_ssm_common_ChatReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_DeliveryChat__Descriptor;

	internal static FieldAccessorTable<DeliveryChat, DeliveryChat.Builder> internal__static_com_sec_ssm_common_DeliveryChat__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_DeliveryChatReply__Descriptor;

	internal static FieldAccessorTable<DeliveryChatReply, DeliveryChatReply.Builder> internal__static_com_sec_ssm_common_DeliveryChatReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_EndChatRequest__Descriptor;

	internal static FieldAccessorTable<EndChatRequest, EndChatRequest.Builder> internal__static_com_sec_ssm_common_EndChatRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_EndChatReply__Descriptor;

	internal static FieldAccessorTable<EndChatReply, EndChatReply.Builder> internal__static_com_sec_ssm_common_EndChatReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_AnswerBack__Descriptor;

	internal static FieldAccessorTable<AnswerBack, AnswerBack.Builder> internal__static_com_sec_ssm_common_AnswerBack__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_AnswerBackReply__Descriptor;

	internal static FieldAccessorTable<AnswerBackReply, AnswerBackReply.Builder> internal__static_com_sec_ssm_common_AnswerBackReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_InviteChatRequest__Descriptor;

	internal static FieldAccessorTable<InviteChatRequest, InviteChatRequest.Builder> internal__static_com_sec_ssm_common_InviteChatRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_InviteChatReply__Descriptor;

	internal static FieldAccessorTable<InviteChatReply, InviteChatReply.Builder> internal__static_com_sec_ssm_common_InviteChatReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_DisconnectRequest__Descriptor;

	internal static FieldAccessorTable<DisconnectRequest, DisconnectRequest.Builder> internal__static_com_sec_ssm_common_DisconnectRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_DisconnectReply__Descriptor;

	internal static FieldAccessorTable<DisconnectReply, DisconnectReply.Builder> internal__static_com_sec_ssm_common_DisconnectReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_AnnounceChange__Descriptor;

	internal static FieldAccessorTable<AnnounceChange, AnnounceChange.Builder> internal__static_com_sec_ssm_common_AnnounceChange__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_AnnounceChangeReply__Descriptor;

	internal static FieldAccessorTable<AnnounceChangeReply, AnnounceChangeReply.Builder> internal__static_com_sec_ssm_common_AnnounceChangeReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_NicknameRequest__Descriptor;

	internal static FieldAccessorTable<NicknameRequest, NicknameRequest.Builder> internal__static_com_sec_ssm_common_NicknameRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_NicknameReply__Descriptor;

	internal static FieldAccessorTable<NicknameReply, NicknameReply.Builder> internal__static_com_sec_ssm_common_NicknameReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_WebProvisionRequest__Descriptor;

	internal static FieldAccessorTable<WebProvisionRequest, WebProvisionRequest.Builder> internal__static_com_sec_ssm_common_WebProvisionRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_WebProvisionReply__Descriptor;

	internal static FieldAccessorTable<WebProvisionReply, WebProvisionReply.Builder> internal__static_com_sec_ssm_common_WebProvisionReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_InvalidUserRequest__Descriptor;

	internal static FieldAccessorTable<InvalidUserRequest, InvalidUserRequest.Builder> internal__static_com_sec_ssm_common_InvalidUserRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_InvalidUserReply__Descriptor;

	internal static FieldAccessorTable<InvalidUserReply, InvalidUserReply.Builder> internal__static_com_sec_ssm_common_InvalidUserReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_IsTyping__Descriptor;

	internal static FieldAccessorTable<IsTyping, IsTyping.Builder> internal__static_com_sec_ssm_common_IsTyping__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_BulkEndChatRequest__Descriptor;

	internal static FieldAccessorTable<BulkEndChatRequest, BulkEndChatRequest.Builder> internal__static_com_sec_ssm_common_BulkEndChatRequest__FieldAccessorTable;

	private static FileDescriptor descriptor;

	public static FileDescriptor Descriptor => descriptor;

	public static void RegisterAllExtensions(ExtensionRegistry registry)
	{
	}

	static SSMGPB()
	{
		byte[] descriptorData = Convert.FromBase64String("CgxTU01HUEIucHJvdG8SEmNvbS5zZWMuc3NtLmNvbW1vbiJDChBNZW1iZXJUcmFuc2l0aW9uEhYKDnByZXZpb3VzTWVtYmVyGAEgASgJEhcKD3RyYW5zaXRlZE1lbWJlchgCIAEoCSKsAQoSU2Vzc2lvbk1lcmdlUmVzdWx0EiEKGWxhc3RTZXNzaW9uTWVyZ2VUaW1lc3RhbXAYASABKAMSFgoOY3VycmVudE1lbWJlcnMYAiADKAkSPwoRbWVtYmVyc2hpcENoYW5nZXMYAyADKAsyJC5jb20uc2VjLnNzbS5jb21tb24uTWVtYmVyVHJhbnNpdGlvbhIaChJ0cmFuc2l0ZWRTZXNzaW9uSWQYBCABKAkicwoGUmVzdWx0EhIKCnJlc3VsdENvZGUYASABKAUSEQoJcmVzdWx0TXNnGAIgASgJEkIKEnNlc3Npb25NZXJnZVJlc3VsdBgDIAEoCzImLmNvbS5zZWMuc3NtLmNvbW1vbi5TZXNzaW9uTWVyZ2VSZXN1bHQiKgoITmlja25hbWUSDAoEdXNlchgBIAEoCRIQCghuaWNrbmFtZRgCIAEoCSLBAQoMSW5ib3hNZXNzYWdlEg4KBnNlbmRlchgBIAEoCRIRCglyZWNlaXZlcnMYAiADKAkSDQoFbXNnSUQYAyABKAMSDwoHY2hhdE1zZxgEIAEoCRIQCghzZW50VGltZRgFIAEoAxIsCgdtc2dUeXBlGAYgASgOMhsuY29tLnNlYy5zc20uY29tbW9uLk1zZ1R5cGUSLgoIY2hhdFR5cGUYByABKA4yHC5jb20uc2VjLnNzbS5jb21tb24uQ2hhdFR5cGUidgoVRGVsaXZlcnlDaGF0UmVwbHlJdGVtEg4KBnNlbmRlchgBIAEoCRIQCghyZWNlaXZlchgCIAEoCRINCgVtc2dJRBgDIAEoAxIsCgdtc2dUeXBlGAQgASgOMhsuY29tLnNlYy5zc20uY29tbW9uLk1zZ1R5cGUiMQoOQW5zd2VyYmFja0l0ZW0SEAoIcmVjZWl2ZXIYASABKAkSDQoFbXNnSUQYAiABKAMiKwoKU2VydmVySW5mbxIPCgdhZGRyZXNzGAEgASgJEgwKBHBvcnQYAiABKAUiYgoQQ2hhbmdlTWVtYmVyTGlzdBIwCgZzdGF0dXMYASABKA4yIC5jb20uc2VjLnNzbS5jb21tb24uQ2hhbmdlU3RhdHVzEg4KBm1lbWJlchgCIAEoCRIMCgRuYW1lGAMgASgJIpIBCghFbmRQYXJhbRINCgVtc2dJRBgBIAEoAxIuCghjaGF0VHlwZRgCIAEoDjIcLmNvbS5zZWMuc3NtLmNvbW1vbi5DaGF0VHlwZRIRCglzZXNzaW9uSUQYAyABKAkSEQoJcmVjZWl2ZXJzGAQgAygJEiEKGWxhc3RTZXNzaW9uTWVyZ2VUaW1lc3RhbXAYBSABKAMi5QEKD0luaXRDaGF0UmVxdWVzdBINCgVtc2dJRBgBIAEoAxIsCgdtc2dUeXBlGAIgASgOMhsuY29tLnNlYy5zc20uY29tbW9uLk1zZ1R5cGUSLgoIY2hhdFR5cGUYAyABKA4yHC5jb20uc2VjLnNzbS5jb21tb24uQ2hhdFR5cGUSCwoDVUlEGAQgASgJEgwKBElNRUkYBSABKAkSFwoPcmVzZXJ2YXRpb25UaW1lGAYgASgDEg4KBnNlbmRlchgHIAEoCRIQCghyZWNlaXZlchgIIAMoCRIPCgdjaGF0TXNnGAkgASgJIqoBCg1Jbml0Q2hhdFJlcGx5Eg0KBW1zZ0lEGAEgASgDEhEKCXNlc3Npb25JRBgCIAEoCRIXCg9tc2dSZWNlaXZlZFRpbWUYAyABKAMSMgoKc2VydmVySW5mbxgEIAEoCzIeLmNvbS5zZWMuc3NtLmNvbW1vbi5TZXJ2ZXJJbmZvEioKBnJlc3VsdBgFIAEoCzIaLmNvbS5zZWMuc3NtLmNvbW1vbi5SZXN1bHQi+wEKEEFsbG93Q2hhdFJlcXVlc3QSDQoFbXNnSUQYASABKAMSLgoIY2hhdFR5cGUYAiABKA4yHC5jb20uc2VjLnNzbS5jb21tb24uQ2hhdFR5cGUSEQoJc2Vzc2lvbklEGAMgASgJEg4KBnNlbmRlchgEIAEoCRIQCghyZWNlaXZlchgFIAEoCRILCgNVSUQYBiABKAkSDAoESU1FSRgHIAEoCRIXCg9tYXhNZXNzYWdlQ291bnQYCCABKAUSHAoUbGFzdE1lc3NhZ2VUaW1lc3RhbXAYCSABKAMSIQoZbGFzdFNlc3Npb25NZXJnZVRpbWVzdGFtcBgKIAEoAyJLCg5BbGxvd0NoYXRSZXBseRINCgVtc2dJRBgBIAEoAxIqCgZyZXN1bHQYAiABKAsyGi5jb20uc2VjLnNzbS5jb21tb24uUmVzdWx0IpcCCgtDaGF0UmVxdWVzdBINCgVtc2dJRBgBIAEoAxIsCgdtc2dUeXBlGAIgASgOMhsuY29tLnNlYy5zc20uY29tbW9uLk1zZ1R5cGUSLgoIY2hhdFR5cGUYAyABKA4yHC5jb20uc2VjLnNzbS5jb21tb24uQ2hhdFR5cGUSEQoJc2Vzc2lvbklEGAQgASgJEg4KBnNlbmRlchgFIAEoCRIQCghyZWNlaXZlchgGIAMoCRILCgNVSUQYByABKAkSDAoESU1FSRgIIAEoCRIPCgdjaGF0TXNnGAkgASgJEhcKD3doaXNwZXJSZWNlaXZlchgKIAEoCRIhChlsYXN0U2Vzc2lvbk1lcmdlVGltZXN0YW1wGAsgASgDIqYBCglDaGF0UmVwbHkSDQoFbXNnSUQYASABKAMSEQoJc2Vzc2lvbklEGAIgASgJEjIKCnNlcnZlckluZm8YAyABKAsyHi5jb20uc2VjLnNzbS5jb21tb24uU2VydmVySW5mbxIXCg9tc2dSZWNlaXZlZFRpbWUYBCABKAMSKgoGcmVzdWx0GAUgASgLMhouY29tLnNlYy5zc20uY29tbW9uLlJlc3VsdCK5AQoMRGVsaXZlcnlDaGF0EhEKCXNlc3Npb25JRBgBIAEoCRIuCghjaGF0VHlwZRgCIAEoDjIcLmNvbS5zZWMuc3NtLmNvbW1vbi5DaGF0VHlwZRI2CgxpbmJveE1lc3NhZ2UYAyADKAsyIC5jb20uc2VjLnNzbS5jb21tb24uSW5ib3hNZXNzYWdlEhcKD3doaXNwZXJSZWNlaXZlchgEIAEoCRIVCg1oYXNNb3JlUmVzdWx0GAUgASgIIs4BChFEZWxpdmVyeUNoYXRSZXBseRILCgNVSUQYASABKAkSSQoWZGVsaXZlcnlDaGF0UmVwbHlJdGVtcxgCIAMoCzIpLmNvbS5zZWMuc3NtLmNvbW1vbi5EZWxpdmVyeUNoYXRSZXBseUl0ZW0SKgoGcmVzdWx0GAMgASgLMhouY29tLnNlYy5zc20uY29tbW9uLlJlc3VsdBIXCg9tYXhNZXNzYWdlQ291bnQYBCABKAUSHAoUbGFzdE1lc3NhZ2VUaW1lc3RhbXAYBSABKAMitQEKDkVuZENoYXRSZXF1ZXN0Eg0KBW1zZ0lEGAEgASgDEi4KCGNoYXRUeXBlGAIgASgOMhwuY29tLnNlYy5zc20uY29tbW9uLkNoYXRUeXBlEhEKCXNlc3Npb25JRBgDIAEoCRILCgNVSUQYBCABKAkSDgoGc2VuZGVyGAUgASgJEhEKCXJlY2VpdmVycxgGIAMoCRIhChlsYXN0U2Vzc2lvbk1lcmdlVGltZXN0YW1wGAcgASgDIkkKDEVuZENoYXRSZXBseRINCgVtc2dJRBgBIAEoAxIqCgZyZXN1bHQYAiABKAsyGi5jb20uc2VjLnNzbS5jb21tb24uUmVzdWx0IkkKCkFuc3dlckJhY2sSOwoPYW5zd2VyYmFja0l0ZW1zGAEgAygLMiIuY29tLnNlYy5zc20uY29tbW9uLkFuc3dlcmJhY2tJdGVtIocBCg9BbnN3ZXJCYWNrUmVwbHkSCwoDVUlEGAEgASgJEjsKD2Fuc3dlcmJhY2tJdGVtcxgCIAMoCzIiLmNvbS5zZWMuc3NtLmNvbW1vbi5BbnN3ZXJiYWNrSXRlbRIqCgZyZXN1bHQYAyABKAsyGi5jb20uc2VjLnNzbS5jb21tb24uUmVzdWx0IsEBChFJbnZpdGVDaGF0UmVxdWVzdBINCgVtc2dJRBgBIAEoAxIsCgdtc2dUeXBlGAIgASgOMhsuY29tLnNlYy5zc20uY29tbW9uLk1zZ1R5cGUSEQoJc2Vzc2lvbklEGAMgASgJEg4KBnNlbmRlchgEIAEoCRIQCghyZWNlaXZlchgFIAMoCRIXCg9pbnZpdGluZ01lbWJlcnMYBiADKAkSIQoZbGFzdFNlc3Npb25NZXJnZVRpbWVzdGFtcBgHIAEoAyJlCg9JbnZpdGVDaGF0UmVwbHkSDQoFbXNnSUQYASABKAMSKgoGcmVzdWx0GAIgASgLMhouY29tLnNlYy5zc20uY29tbW9uLlJlc3VsdBIXCg9Nc2dSZWNlaXZlZFRpbWUYAyABKAMicQoRRGlzY29ubmVjdFJlcXVlc3QSDQoFbXNnSUQYASABKAMSOgoOZGlzY29ubmVjdFR5cGUYAiABKA4yIi5jb20uc2VjLnNzbS5jb21tb24uRGlzY29ubmVjdFR5cGUSEQoJc2Vzc2lvbklEGAMgASgJIpQBCg9EaXNjb25uZWN0UmVwbHkSDQoFbXNnSUQYASABKAMSRgoUZGlzY29ubmVjdEFjdGlvblR5cGUYAiABKA4yKC5jb20uc2VjLnNzbS5jb21tb24uRGlzY29ubmVjdEFjdGlvblR5cGUSKgoGcmVzdWx0GAMgASgLMhouY29tLnNlYy5zc20uY29tbW9uLlJlc3VsdCKuAQoOQW5ub3VuY2VDaGFuZ2USDQoFbXNnSUQYASABKAMSEQoJc2Vzc2lvbklEGAIgASgJEj4KEGNoYW5nZU1lbWJlckxpc3QYAyADKAsyJC5jb20uc2VjLnNzbS5jb21tb24uQ2hhbmdlTWVtYmVyTGlzdBIXCg9Hcm91cE1lbWJlckxpc3QYBCADKAkSEAoIc2VudFRpbWUYBSABKAMSDwoHaW52aXRlchgGIAEoCSJQChNBbm5vdW5jZUNoYW5nZVJlcGx5Eg0KBW1zZ0lEGAEgASgDEioKBnJlc3VsdBgCIAEoCzIaLmNvbS5zZWMuc3NtLmNvbW1vbi5SZXN1bHQiLgoPTmlja25hbWVSZXF1ZXN0Eg0KBW1zZ0lEGAEgASgDEgwKBHVzZXIYAiADKAkiegoNTmlja25hbWVSZXBseRINCgVtc2dJRBgBIAEoAxIuCghuaWNrbmFtZRgCIAMoCzIcLmNvbS5zZWMuc3NtLmNvbW1vbi5OaWNrbmFtZRIqCgZyZXN1bHQYAyABKAsyGi5jb20uc2VjLnNzbS5jb21tb24uUmVzdWx0ImIKE1dlYlByb3Zpc2lvblJlcXVlc3QSDQoFbXNnSUQYASABKAMSCwoDVUlEGAIgASgJEgwKBElNRUkYAyABKAkSEAoIcmVjZWl2ZXIYBCABKAkSDwoHY2hhdE1zZxgFIAEoCSJbChFXZWJQcm92aXNpb25SZXBseRINCgVtc2dJRBgBIAEoAxILCgNVSUQYAiABKAkSKgoGcmVzdWx0GAMgASgLMhouY29tLnNlYy5zc20uY29tbW9uLlJlc3VsdCIyChJJbnZhbGlkVXNlclJlcXVlc3QSDQoFbXNnSUQYASABKAMSDQoFdXNlcnMYAiADKAkiYwoQSW52YWxpZFVzZXJSZXBseRINCgVtc2dJRBgBIAEoAxIUCgxpbnZhbGlkVXNlcnMYAiADKAkSKgoGcmVzdWx0GAMgASgLMhouY29tLnNlYy5zc20uY29tbW9uLlJlc3VsdCKzAQoISXNUeXBpbmcSLgoIY2hhdFR5cGUYASABKA4yHC5jb20uc2VjLnNzbS5jb21tb24uQ2hhdFR5cGUSEQoJc2Vzc2lvbklEGAIgASgJEg4KBnNlbmRlchgDIAEoCRINCgVzdGF0ZRgEIAEoCRI0Cgtjb250ZW50VHlwZRgFIAEoDjIfLmNvbS5zZWMuc3NtLmNvbW1vbi5Db250ZW50VHlwZRIPCgdyZWZyZXNoGAYgASgFImIKEkJ1bGtFbmRDaGF0UmVxdWVzdBILCgNVSUQYASABKAkSDgoGc2VuZGVyGAIgASgJEi8KCWVuZFBhcmFtcxgDIAMoCzIcLmNvbS5zZWMuc3NtLmNvbW1vbi5FbmRQYXJhbSowCghDaGF0VHlwZRIKCgZTSU5HTEUQABIJCgVHUk9VUBABEg0KCUJST0FEQ0FTVBACKj4KB01zZ1R5cGUSCAoEVEVYVBAAEgkKBU1FRElBEAESCAoETk9USRACEgcKA0FOUxADEgsKB01FU1NBR0UQBCpYCgtDb250ZW50VHlwZRIQCgxDT05URU5UX1RFWFQQABIRCg1DT05URU5UX0lNQUdFEAESEQoNQ09OVEVOVF9WSURFTxACEhEKDUNPTlRFTlRfQVVESU8QAyowCg5EaXNjb25uZWN0VHlwZRILCgdUSU1FT1VUEAASEQoNR1JPVVBDSEFUX0VORBABKi4KFERpc2Nvbm5lY3RBY3Rpb25UeXBlEgkKBUNMT1NFEAASCwoHSE9MRF9PThABKiQKDENoYW5nZVN0YXR1cxIJCgVFTlRFUhAAEgkKBUxFQVZFEAFCJwoYY29tLnNlYy5zc20ubXNnLmZyb250ZW5kQgtNc2dGcm9udGVuZA==");
		FileDescriptor.InternalDescriptorAssigner descriptorAssigner = delegate(FileDescriptor root)
		{
			descriptor = root;
			internal__static_com_sec_ssm_common_MemberTransition__Descriptor = Descriptor.MessageTypes[0];
			internal__static_com_sec_ssm_common_MemberTransition__FieldAccessorTable = new FieldAccessorTable<MemberTransition, MemberTransition.Builder>(internal__static_com_sec_ssm_common_MemberTransition__Descriptor, new string[2] { "PreviousMember", "TransitedMember" });
			internal__static_com_sec_ssm_common_SessionMergeResult__Descriptor = Descriptor.MessageTypes[1];
			internal__static_com_sec_ssm_common_SessionMergeResult__FieldAccessorTable = new FieldAccessorTable<SessionMergeResult, SessionMergeResult.Builder>(internal__static_com_sec_ssm_common_SessionMergeResult__Descriptor, new string[4] { "LastSessionMergeTimestamp", "CurrentMembers", "MembershipChanges", "TransitedSessionId" });
			internal__static_com_sec_ssm_common_Result__Descriptor = Descriptor.MessageTypes[2];
			internal__static_com_sec_ssm_common_Result__FieldAccessorTable = new FieldAccessorTable<Result, Result.Builder>(internal__static_com_sec_ssm_common_Result__Descriptor, new string[3] { "ResultCode", "ResultMsg", "SessionMergeResult" });
			internal__static_com_sec_ssm_common_Nickname__Descriptor = Descriptor.MessageTypes[3];
			internal__static_com_sec_ssm_common_Nickname__FieldAccessorTable = new FieldAccessorTable<Nickname, Nickname.Builder>(internal__static_com_sec_ssm_common_Nickname__Descriptor, new string[2] { "User", "Nickname_" });
			internal__static_com_sec_ssm_common_InboxMessage__Descriptor = Descriptor.MessageTypes[4];
			internal__static_com_sec_ssm_common_InboxMessage__FieldAccessorTable = new FieldAccessorTable<InboxMessage, InboxMessage.Builder>(internal__static_com_sec_ssm_common_InboxMessage__Descriptor, new string[7] { "Sender", "Receivers", "MsgID", "ChatMsg", "SentTime", "MsgType", "ChatType" });
			internal__static_com_sec_ssm_common_DeliveryChatReplyItem__Descriptor = Descriptor.MessageTypes[5];
			internal__static_com_sec_ssm_common_DeliveryChatReplyItem__FieldAccessorTable = new FieldAccessorTable<DeliveryChatReplyItem, DeliveryChatReplyItem.Builder>(internal__static_com_sec_ssm_common_DeliveryChatReplyItem__Descriptor, new string[4] { "Sender", "Receiver", "MsgID", "MsgType" });
			internal__static_com_sec_ssm_common_AnswerbackItem__Descriptor = Descriptor.MessageTypes[6];
			internal__static_com_sec_ssm_common_AnswerbackItem__FieldAccessorTable = new FieldAccessorTable<AnswerbackItem, AnswerbackItem.Builder>(internal__static_com_sec_ssm_common_AnswerbackItem__Descriptor, new string[2] { "Receiver", "MsgID" });
			internal__static_com_sec_ssm_common_ServerInfo__Descriptor = Descriptor.MessageTypes[7];
			internal__static_com_sec_ssm_common_ServerInfo__FieldAccessorTable = new FieldAccessorTable<ServerInfo, ServerInfo.Builder>(internal__static_com_sec_ssm_common_ServerInfo__Descriptor, new string[2] { "Address", "Port" });
			internal__static_com_sec_ssm_common_ChangeMemberList__Descriptor = Descriptor.MessageTypes[8];
			internal__static_com_sec_ssm_common_ChangeMemberList__FieldAccessorTable = new FieldAccessorTable<ChangeMemberList, ChangeMemberList.Builder>(internal__static_com_sec_ssm_common_ChangeMemberList__Descriptor, new string[3] { "Status", "Member", "Name" });
			internal__static_com_sec_ssm_common_EndParam__Descriptor = Descriptor.MessageTypes[9];
			internal__static_com_sec_ssm_common_EndParam__FieldAccessorTable = new FieldAccessorTable<EndParam, EndParam.Builder>(internal__static_com_sec_ssm_common_EndParam__Descriptor, new string[5] { "MsgID", "ChatType", "SessionID", "Receivers", "LastSessionMergeTimestamp" });
			internal__static_com_sec_ssm_common_InitChatRequest__Descriptor = Descriptor.MessageTypes[10];
			internal__static_com_sec_ssm_common_InitChatRequest__FieldAccessorTable = new FieldAccessorTable<InitChatRequest, InitChatRequest.Builder>(internal__static_com_sec_ssm_common_InitChatRequest__Descriptor, new string[9] { "MsgID", "MsgType", "ChatType", "UID", "IMEI", "ReservationTime", "Sender", "Receiver", "ChatMsg" });
			internal__static_com_sec_ssm_common_InitChatReply__Descriptor = Descriptor.MessageTypes[11];
			internal__static_com_sec_ssm_common_InitChatReply__FieldAccessorTable = new FieldAccessorTable<InitChatReply, InitChatReply.Builder>(internal__static_com_sec_ssm_common_InitChatReply__Descriptor, new string[5] { "MsgID", "SessionID", "MsgReceivedTime", "ServerInfo", "Result" });
			internal__static_com_sec_ssm_common_AllowChatRequest__Descriptor = Descriptor.MessageTypes[12];
			internal__static_com_sec_ssm_common_AllowChatRequest__FieldAccessorTable = new FieldAccessorTable<AllowChatRequest, AllowChatRequest.Builder>(internal__static_com_sec_ssm_common_AllowChatRequest__Descriptor, new string[10] { "MsgID", "ChatType", "SessionID", "Sender", "Receiver", "UID", "IMEI", "MaxMessageCount", "LastMessageTimestamp", "LastSessionMergeTimestamp" });
			internal__static_com_sec_ssm_common_AllowChatReply__Descriptor = Descriptor.MessageTypes[13];
			internal__static_com_sec_ssm_common_AllowChatReply__FieldAccessorTable = new FieldAccessorTable<AllowChatReply, AllowChatReply.Builder>(internal__static_com_sec_ssm_common_AllowChatReply__Descriptor, new string[2] { "MsgID", "Result" });
			internal__static_com_sec_ssm_common_ChatRequest__Descriptor = Descriptor.MessageTypes[14];
			internal__static_com_sec_ssm_common_ChatRequest__FieldAccessorTable = new FieldAccessorTable<ChatRequest, ChatRequest.Builder>(internal__static_com_sec_ssm_common_ChatRequest__Descriptor, new string[11]
			{
				"MsgID", "MsgType", "ChatType", "SessionID", "Sender", "Receiver", "UID", "IMEI", "ChatMsg", "WhisperReceiver",
				"LastSessionMergeTimestamp"
			});
			internal__static_com_sec_ssm_common_ChatReply__Descriptor = Descriptor.MessageTypes[15];
			internal__static_com_sec_ssm_common_ChatReply__FieldAccessorTable = new FieldAccessorTable<ChatReply, ChatReply.Builder>(internal__static_com_sec_ssm_common_ChatReply__Descriptor, new string[5] { "MsgID", "SessionID", "ServerInfo", "MsgReceivedTime", "Result" });
			internal__static_com_sec_ssm_common_DeliveryChat__Descriptor = Descriptor.MessageTypes[16];
			internal__static_com_sec_ssm_common_DeliveryChat__FieldAccessorTable = new FieldAccessorTable<DeliveryChat, DeliveryChat.Builder>(internal__static_com_sec_ssm_common_DeliveryChat__Descriptor, new string[5] { "SessionID", "ChatType", "InboxMessage", "WhisperReceiver", "HasMoreResult" });
			internal__static_com_sec_ssm_common_DeliveryChatReply__Descriptor = Descriptor.MessageTypes[17];
			internal__static_com_sec_ssm_common_DeliveryChatReply__FieldAccessorTable = new FieldAccessorTable<DeliveryChatReply, DeliveryChatReply.Builder>(internal__static_com_sec_ssm_common_DeliveryChatReply__Descriptor, new string[5] { "UID", "DeliveryChatReplyItems", "Result", "MaxMessageCount", "LastMessageTimestamp" });
			internal__static_com_sec_ssm_common_EndChatRequest__Descriptor = Descriptor.MessageTypes[18];
			internal__static_com_sec_ssm_common_EndChatRequest__FieldAccessorTable = new FieldAccessorTable<EndChatRequest, EndChatRequest.Builder>(internal__static_com_sec_ssm_common_EndChatRequest__Descriptor, new string[7] { "MsgID", "ChatType", "SessionID", "UID", "Sender", "Receivers", "LastSessionMergeTimestamp" });
			internal__static_com_sec_ssm_common_EndChatReply__Descriptor = Descriptor.MessageTypes[19];
			internal__static_com_sec_ssm_common_EndChatReply__FieldAccessorTable = new FieldAccessorTable<EndChatReply, EndChatReply.Builder>(internal__static_com_sec_ssm_common_EndChatReply__Descriptor, new string[2] { "MsgID", "Result" });
			internal__static_com_sec_ssm_common_AnswerBack__Descriptor = Descriptor.MessageTypes[20];
			internal__static_com_sec_ssm_common_AnswerBack__FieldAccessorTable = new FieldAccessorTable<AnswerBack, AnswerBack.Builder>(internal__static_com_sec_ssm_common_AnswerBack__Descriptor, new string[1] { "AnswerbackItems" });
			internal__static_com_sec_ssm_common_AnswerBackReply__Descriptor = Descriptor.MessageTypes[21];
			internal__static_com_sec_ssm_common_AnswerBackReply__FieldAccessorTable = new FieldAccessorTable<AnswerBackReply, AnswerBackReply.Builder>(internal__static_com_sec_ssm_common_AnswerBackReply__Descriptor, new string[3] { "UID", "AnswerbackItems", "Result" });
			internal__static_com_sec_ssm_common_InviteChatRequest__Descriptor = Descriptor.MessageTypes[22];
			internal__static_com_sec_ssm_common_InviteChatRequest__FieldAccessorTable = new FieldAccessorTable<InviteChatRequest, InviteChatRequest.Builder>(internal__static_com_sec_ssm_common_InviteChatRequest__Descriptor, new string[7] { "MsgID", "MsgType", "SessionID", "Sender", "Receiver", "InvitingMembers", "LastSessionMergeTimestamp" });
			internal__static_com_sec_ssm_common_InviteChatReply__Descriptor = Descriptor.MessageTypes[23];
			internal__static_com_sec_ssm_common_InviteChatReply__FieldAccessorTable = new FieldAccessorTable<InviteChatReply, InviteChatReply.Builder>(internal__static_com_sec_ssm_common_InviteChatReply__Descriptor, new string[3] { "MsgID", "Result", "MsgReceivedTime" });
			internal__static_com_sec_ssm_common_DisconnectRequest__Descriptor = Descriptor.MessageTypes[24];
			internal__static_com_sec_ssm_common_DisconnectRequest__FieldAccessorTable = new FieldAccessorTable<DisconnectRequest, DisconnectRequest.Builder>(internal__static_com_sec_ssm_common_DisconnectRequest__Descriptor, new string[3] { "MsgID", "DisconnectType", "SessionID" });
			internal__static_com_sec_ssm_common_DisconnectReply__Descriptor = Descriptor.MessageTypes[25];
			internal__static_com_sec_ssm_common_DisconnectReply__FieldAccessorTable = new FieldAccessorTable<DisconnectReply, DisconnectReply.Builder>(internal__static_com_sec_ssm_common_DisconnectReply__Descriptor, new string[3] { "MsgID", "DisconnectActionType", "Result" });
			internal__static_com_sec_ssm_common_AnnounceChange__Descriptor = Descriptor.MessageTypes[26];
			internal__static_com_sec_ssm_common_AnnounceChange__FieldAccessorTable = new FieldAccessorTable<AnnounceChange, AnnounceChange.Builder>(internal__static_com_sec_ssm_common_AnnounceChange__Descriptor, new string[6] { "MsgID", "SessionID", "ChangeMemberList", "GroupMemberList", "SentTime", "Inviter" });
			internal__static_com_sec_ssm_common_AnnounceChangeReply__Descriptor = Descriptor.MessageTypes[27];
			internal__static_com_sec_ssm_common_AnnounceChangeReply__FieldAccessorTable = new FieldAccessorTable<AnnounceChangeReply, AnnounceChangeReply.Builder>(internal__static_com_sec_ssm_common_AnnounceChangeReply__Descriptor, new string[2] { "MsgID", "Result" });
			internal__static_com_sec_ssm_common_NicknameRequest__Descriptor = Descriptor.MessageTypes[28];
			internal__static_com_sec_ssm_common_NicknameRequest__FieldAccessorTable = new FieldAccessorTable<NicknameRequest, NicknameRequest.Builder>(internal__static_com_sec_ssm_common_NicknameRequest__Descriptor, new string[2] { "MsgID", "User" });
			internal__static_com_sec_ssm_common_NicknameReply__Descriptor = Descriptor.MessageTypes[29];
			internal__static_com_sec_ssm_common_NicknameReply__FieldAccessorTable = new FieldAccessorTable<NicknameReply, NicknameReply.Builder>(internal__static_com_sec_ssm_common_NicknameReply__Descriptor, new string[3] { "MsgID", "Nickname", "Result" });
			internal__static_com_sec_ssm_common_WebProvisionRequest__Descriptor = Descriptor.MessageTypes[30];
			internal__static_com_sec_ssm_common_WebProvisionRequest__FieldAccessorTable = new FieldAccessorTable<WebProvisionRequest, WebProvisionRequest.Builder>(internal__static_com_sec_ssm_common_WebProvisionRequest__Descriptor, new string[5] { "MsgID", "UID", "IMEI", "Receiver", "ChatMsg" });
			internal__static_com_sec_ssm_common_WebProvisionReply__Descriptor = Descriptor.MessageTypes[31];
			internal__static_com_sec_ssm_common_WebProvisionReply__FieldAccessorTable = new FieldAccessorTable<WebProvisionReply, WebProvisionReply.Builder>(internal__static_com_sec_ssm_common_WebProvisionReply__Descriptor, new string[3] { "MsgID", "UID", "Result" });
			internal__static_com_sec_ssm_common_InvalidUserRequest__Descriptor = Descriptor.MessageTypes[32];
			internal__static_com_sec_ssm_common_InvalidUserRequest__FieldAccessorTable = new FieldAccessorTable<InvalidUserRequest, InvalidUserRequest.Builder>(internal__static_com_sec_ssm_common_InvalidUserRequest__Descriptor, new string[2] { "MsgID", "Users" });
			internal__static_com_sec_ssm_common_InvalidUserReply__Descriptor = Descriptor.MessageTypes[33];
			internal__static_com_sec_ssm_common_InvalidUserReply__FieldAccessorTable = new FieldAccessorTable<InvalidUserReply, InvalidUserReply.Builder>(internal__static_com_sec_ssm_common_InvalidUserReply__Descriptor, new string[3] { "MsgID", "InvalidUsers", "Result" });
			internal__static_com_sec_ssm_common_IsTyping__Descriptor = Descriptor.MessageTypes[34];
			internal__static_com_sec_ssm_common_IsTyping__FieldAccessorTable = new FieldAccessorTable<IsTyping, IsTyping.Builder>(internal__static_com_sec_ssm_common_IsTyping__Descriptor, new string[6] { "ChatType", "SessionID", "Sender", "State", "ContentType", "Refresh" });
			internal__static_com_sec_ssm_common_BulkEndChatRequest__Descriptor = Descriptor.MessageTypes[35];
			internal__static_com_sec_ssm_common_BulkEndChatRequest__FieldAccessorTable = new FieldAccessorTable<BulkEndChatRequest, BulkEndChatRequest.Builder>(internal__static_com_sec_ssm_common_BulkEndChatRequest__Descriptor, new string[3] { "UID", "Sender", "EndParams" });
			return (ExtensionRegistry)null;
		};
		FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData, new FileDescriptor[0], descriptorAssigner);
	}
}
