package com.sec.chaton.p025d;

/* compiled from: DatabaseHelper.java */
/* renamed from: com.sec.chaton.d.e */
/* loaded from: classes.dex */
public interface InterfaceC0652e {

    /* renamed from: a */
    public static final String f2275a = "(SELECT *FROM(SELECT ifnull(b.buddy_name,'') AS buddy_name,ifnull(b.buddy_no,a.message_sender) AS buddy_no,ifnull(b.buddy_status_message,'') AS buddy_status_message,ifnull(b.buddy_profile_status,'') AS buddy_profile_status,a.message_content,a.message_content_type,a.message_download_uri,a.message_formatted,a._id,a.message_inbox_no,a.message_read_status,a.message_sender,a.message_sever_id,a.message_session_id,a.message_time,a.message_translated,a.message_stored_ext,a.message_is_failed,a.message_type FROM message a LEFT OUTER JOIN (SELECT buddy_no,buddy_name,buddy_status_message,buddy_profile_status FROM buddy UNION ALL SELECT participants_buddy_no AS buddy_no,MAX(participants_buddy_name) AS buddy_name,'' AS buddy_status_message,'' AS buddy_profile_status FROM participant WHERE participants_buddy_no NOT IN (SELECT buddy_no FROM buddy) GROUP BY participants_buddy_no) b ON a.message_sender = b.buddy_no) c LEFT OUTER JOIN (SELECT b.participants_inbox_no AS inbox_no FROM (SELECT participants_buddy_no,participants_inbox_no FROM participant WHERE participants_inbox_no IN (SELECT inbox_no FROM inbox WHERE inbox_chat_type = " + String.valueOf(EnumC0665r.ONETOONE.m3012a()) + ")) b LEFT OUTER JOIN buddy a ON b.participants_buddy_no = a.buddy_no) d ON c.message_inbox_no = d.inbox_no)";

    /* renamed from: b */
    public static final String f2276b = "SELECT * FROM(SELECT ifnull(b.buddy_name,'') AS buddy_name,ifnull(b.buddy_no,a.message_sender) AS buddy_no,ifnull(b.buddy_status_message,'') AS buddy_status_message,ifnull(b.buddy_show_phone_number," + String.valueOf(1) + ") AS buddy_show_phone_number,ifnull(b.buddy_profile_status,'') AS buddy_profile_status,a.message_content,a.message_content_type,a.message_download_uri,a.message_formatted,a._id,a.message_inbox_no,a.message_read_status,a.message_sender,a.message_sever_id,a.message_session_id,a.message_time,a.message_translated,a.message_stored_ext,a.message_is_failed,a.message_type FROM ( SELECT * FROM message WHERE message_inbox_no = ? ORDER BY message_is_failed DESC , message_time DESC , _id DESC LIMIT ? ) a LEFT OUTER JOIN (SELECT buddy_no,buddy_name,buddy_status_message,buddy_show_phone_number,buddy_profile_status FROM buddy UNION ALL SELECT participants_buddy_no AS buddy_no,MAX(participants_buddy_name) AS buddy_name,'' AS buddy_status_message,'' AS buddy_show_phone_number,'' AS buddy_profile_status FROM participant WHERE participants_buddy_no NOT IN (SELECT buddy_no FROM buddy) GROUP BY participants_buddy_no) b ON a.message_sender = b.buddy_no) c LEFT OUTER JOIN (SELECT ifnull(a.buddy_show_phone_number," + String.valueOf(1) + ") AS opponent_show_phone_number,b.participants_inbox_no AS inbox_no FROM (SELECT participants_buddy_no,participants_inbox_no FROM participant WHERE participants_inbox_no IN (SELECT inbox_no FROM inbox WHERE inbox_chat_type = " + String.valueOf(EnumC0665r.ONETOONE.m3012a()) + ")) b LEFT OUTER JOIN buddy a ON b.participants_buddy_no = a.buddy_no) d ON c.message_inbox_no = d.inbox_no ORDER BY message_is_failed , message_time , _id";

    /* renamed from: c */
    public static final String f2277c = "SELECT message_total_count, ifnull(message_sent_count, 0) AS message_sent_count, ifnull(a.message_inbox_no, b.message_inbox_no) AS message_inbox_no FROM ( ( SELECT count(*) AS message_total_count, message_inbox_no FROM message WHERE message_inbox_no = ? AND message_content_type != " + Integer.toString(EnumC0651d.SYSTEM.m2978a()) + " ) a LEFT OUTER JOIN ( SELECT count(*) AS message_sent_count, message_inbox_no FROM message WHERE message_inbox_no = ? AND message_content_type != " + Integer.toString(EnumC0651d.SYSTEM.m2978a()) + " AND message_sender = ?  ) b ON a.message_inbox_no = b.message_inbox_no )";
}
