namespace ChatON_WoA.DataModel;

public class FeedbackEvent
{
	public enum FeedbackID
	{
		CLICKED = 80,
		WRONGMETADATA = -24,
		DISAGREE = -32,
		UNSUPPORTED_ACTION_TYPE = -37,
		CLIENT_INTERNAL_ERROR = -120
	}

	public enum ServerResponseCode
	{
		RESPONSE_OK = 200,
		RESPONSE_BAD_REQUEST = 400,
		RESPONSE_UNAUTHORIZED = 401,
		RESPONSE_FORBIDDEN = 403,
		RESPONSE_NOT_FOUND = 404,
		RESPONSE_METHOD_NOT_ALLOWED = 405,
		RESPONSE_NOT_ACCEPTABLE = 406,
		RESPONSE_REQUEST_TIMEOUT = 408,
		RESPONSE_LENGTH_REQUIRED = 411,
		RESPONSE_PRECONDITION_FAILED = 412,
		RESPONSE_REQUEST_ENTITY_TOO_LARGE = 413,
		RESPONSE_REQUEST_URI_TOO_LARGE = 414,
		RESPONSE_UNSUPPORTED_MEDIA_TYPE = 415,
		RESPONSE_REQUEST_RANGE_NOT_SATISFIABLE = 416,
		RESPONSE_REQUEST_INVALID_PARAMETER = 460,
		RESPONSE_REQUEST_BLACKLIST_DEVICE = 470,
		RESPONSE_REQUEST_BLACKLIST_MODEL = 471,
		RESPONSE_REQUEST_BLACKLIST_MCC = 472,
		RESPONSE_REQUEST_BLACKLIST_MNC = 473,
		RESPONSE_REQUEST_NONE_REGISTERED_APP = 480,
		RESPONSE_REQUEST_NONE_REGISTERED_REGID = 481,
		RESPONSE_REQUEST_NONE_TARGETED_REGID = 482,
		RESPONSE_REQUEST_NONE_REGISTERED_MID = 483,
		RESPONSE_REQUEST_NONE_AGREED_APP = 484,
		RESPONSE_REQUEST_INVALID_BIGJOE_APPID = 485,
		RESPONSE_INTERNAL_SERVER_ERROR = 500,
		RESPONSE_NOT_IMPLEMENTED = 501,
		RESPONSE_BAD_GATEWAY = 502,
		RESPONSE_SERVICE_UNAVAILABLE = 503,
		RESPONSE_GATEWAY_TIME_OUT = 504,
		RESPONSE_TEST = 999,
		RESPONSE_TEST2 = 999
	}
}
