namespace Microsoft.Phone.Controls;

internal enum PerfMarkerEvents
{
	MPC_PANO_MEASURE = 501,
	MPC_PANO_ARRANGE = 502,
	MPC_PANO_STARTUP = 503,
	MPC_PANO_APPLYTEMPLATE = 504,
	MPC_PANO_UPDATEWRAPPING = 505,
	MPC_PIVOT_MEASURE = 601,
	MPC_PIVOT_ARRANGE = 602,
	MPC_PIVOT_STARTUP = 603,
	MPC_PIVOT_APPLYTEMPLATE = 604
}
