using System;
using Google.ProtocolBuffers;
using Google.ProtocolBuffers.Descriptors;
using Google.ProtocolBuffers.FieldAccess;

namespace com.sec.ssm.common;

public static class SSMGPB
{
	internal static MessageDescriptor internal__static_com_sec_ssm_common_Result__Descriptor;

	internal static FieldAccessorTable<Result, Result.Builder> internal__static_com_sec_ssm_common_Result__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_Nickname__Descriptor;

	internal static FieldAccessorTable<Nickname, Nickname.Builder> internal__static_com_sec_ssm_common_Nickname__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_InboxMessage__Descriptor;

	internal static FieldAccessorTable<InboxMessage, InboxMessage.Builder> internal__static_com_sec_ssm_common_InboxMessage__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_DeliveryChatReplyItem__Descriptor;

	internal static FieldAccessorTable<DeliveryChatReplyItem, DeliveryChatReplyItem.Builder> internal__static_com_sec_ssm_common_DeliveryChatReplyItem__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_AnswerbackItem__Descriptor;

	internal static FieldAccessorTable<AnswerbackItem, AnswerbackItem.Builder> internal__static_com_sec_ssm_common_AnswerbackItem__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_ServerInfo__Descriptor;

	internal static FieldAccessorTable<ServerInfo, ServerInfo.Builder> internal__static_com_sec_ssm_common_ServerInfo__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_ChangeMemberList__Descriptor;

	internal static FieldAccessorTable<ChangeMemberList, ChangeMemberList.Builder> internal__static_com_sec_ssm_common_ChangeMemberList__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_InitChatRequest__Descriptor;

	internal static FieldAccessorTable<InitChatRequest, InitChatRequest.Builder> internal__static_com_sec_ssm_common_InitChatRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_InitChatReply__Descriptor;

	internal static FieldAccessorTable<InitChatReply, InitChatReply.Builder> internal__static_com_sec_ssm_common_InitChatReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_AllowChatRequest__Descriptor;

	internal static FieldAccessorTable<AllowChatRequest, AllowChatRequest.Builder> internal__static_com_sec_ssm_common_AllowChatRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_AllowChatReply__Descriptor;

	internal static FieldAccessorTable<AllowChatReply, AllowChatReply.Builder> internal__static_com_sec_ssm_common_AllowChatReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_ChatRequest__Descriptor;

	internal static FieldAccessorTable<ChatRequest, ChatRequest.Builder> internal__static_com_sec_ssm_common_ChatRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_ChatReply__Descriptor;

	internal static FieldAccessorTable<ChatReply, ChatReply.Builder> internal__static_com_sec_ssm_common_ChatReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_DeliveryChat__Descriptor;

	internal static FieldAccessorTable<DeliveryChat, DeliveryChat.Builder> internal__static_com_sec_ssm_common_DeliveryChat__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_DeliveryChatReply__Descriptor;

	internal static FieldAccessorTable<DeliveryChatReply, DeliveryChatReply.Builder> internal__static_com_sec_ssm_common_DeliveryChatReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_EndChatRequest__Descriptor;

	internal static FieldAccessorTable<EndChatRequest, EndChatRequest.Builder> internal__static_com_sec_ssm_common_EndChatRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_EndChatReply__Descriptor;

	internal static FieldAccessorTable<EndChatReply, EndChatReply.Builder> internal__static_com_sec_ssm_common_EndChatReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_AnswerBack__Descriptor;

	internal static FieldAccessorTable<AnswerBack, AnswerBack.Builder> internal__static_com_sec_ssm_common_AnswerBack__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_AnswerBackReply__Descriptor;

	internal static FieldAccessorTable<AnswerBackReply, AnswerBackReply.Builder> internal__static_com_sec_ssm_common_AnswerBackReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_InviteChatRequest__Descriptor;

	internal static FieldAccessorTable<InviteChatRequest, InviteChatRequest.Builder> internal__static_com_sec_ssm_common_InviteChatRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_InviteChatReply__Descriptor;

	internal static FieldAccessorTable<InviteChatReply, InviteChatReply.Builder> internal__static_com_sec_ssm_common_InviteChatReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_DisconnectRequest__Descriptor;

	internal static FieldAccessorTable<DisconnectRequest, DisconnectRequest.Builder> internal__static_com_sec_ssm_common_DisconnectRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_DisconnectReply__Descriptor;

	internal static FieldAccessorTable<DisconnectReply, DisconnectReply.Builder> internal__static_com_sec_ssm_common_DisconnectReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_AnnounceChange__Descriptor;

	internal static FieldAccessorTable<AnnounceChange, AnnounceChange.Builder> internal__static_com_sec_ssm_common_AnnounceChange__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_AnnounceChangeReply__Descriptor;

	internal static FieldAccessorTable<AnnounceChangeReply, AnnounceChangeReply.Builder> internal__static_com_sec_ssm_common_AnnounceChangeReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_NicknameRequest__Descriptor;

	internal static FieldAccessorTable<NicknameRequest, NicknameRequest.Builder> internal__static_com_sec_ssm_common_NicknameRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_NicknameReply__Descriptor;

	internal static FieldAccessorTable<NicknameReply, NicknameReply.Builder> internal__static_com_sec_ssm_common_NicknameReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_WebProvisionRequest__Descriptor;

	internal static FieldAccessorTable<WebProvisionRequest, WebProvisionRequest.Builder> internal__static_com_sec_ssm_common_WebProvisionRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_WebProvisionReply__Descriptor;

	internal static FieldAccessorTable<WebProvisionReply, WebProvisionReply.Builder> internal__static_com_sec_ssm_common_WebProvisionReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_InvalidUserRequest__Descriptor;

	internal static FieldAccessorTable<InvalidUserRequest, InvalidUserRequest.Builder> internal__static_com_sec_ssm_common_InvalidUserRequest__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_InvalidUserReply__Descriptor;

	internal static FieldAccessorTable<InvalidUserReply, InvalidUserReply.Builder> internal__static_com_sec_ssm_common_InvalidUserReply__FieldAccessorTable;

	internal static MessageDescriptor internal__static_com_sec_ssm_common_System_ReadyToTerminate__Descriptor;

	internal static FieldAccessorTable<System_ReadyToTerminate, System_ReadyToTerminate.Builder> internal__static_com_sec_ssm_common_System_ReadyToTerminate__FieldAccessorTable;

	private static FileDescriptor descriptor;

	public static FileDescriptor Descriptor => descriptor;

	public static void RegisterAllExtensions(ExtensionRegistry registry)
	{
	}

	static SSMGPB()
	{
		byte[] descriptorData = Convert.FromBase64String("ChV0dXRvcmlhbC9TU01HUEIucHJvdG8SEmNvbS5zZWMuc3NtLmNvbW1vbiIvCgZSZXN1bHQSEgoKcmVzdWx0Q29kZRgBIAEoBRIRCglyZXN1bHRNc2cYAiABKAkiKgoITmlja25hbWUSDAoEdXNlchgBIAEoCRIQCghuaWNrbmFtZRgCIAEoCSLBAQoMSW5ib3hNZXNzYWdlEg4KBnNlbmRlchgBIAEoCRIRCglyZWNlaXZlcnMYAiADKAkSDQoFbXNnSUQYAyABKAMSDwoHY2hhdE1zZxgEIAEoCRIQCghzZW50VGltZRgFIAEoAxIsCgdtc2dUeXBlGAYgASgOMhsuY29tLnNlYy5zc20uY29tbW9uLk1zZ1R5cGUSLgoIY2hhdFR5cGUYByABKA4yHC5jb20uc2VjLnNzbS5jb21tb24uQ2hhdFR5cGUidgoVRGVsaXZlcnlDaGF0UmVwbHlJdGVtEg4KBnNlbmRlchgBIAEoCRIQCghyZWNlaXZlchgCIAEoCRINCgVtc2dJRBgDIAEoAxIsCgdtc2dUeXBlGAQgASgOMhsuY29tLnNlYy5zc20uY29tbW9uLk1zZ1R5cGUiMQoOQW5zd2VyYmFja0l0ZW0SEAoIcmVjZWl2ZXIYASABKAkSDQoFbXNnSUQYAiABKAMiKwoKU2VydmVySW5mbxIPCgdhZGRyZXNzGAEgASgJEgwKBHBvcnQYAiABKAUiYgoQQ2hhbmdlTWVtYmVyTGlzdBIwCgZzdGF0dXMYASABKA4yIC5jb20uc2VjLnNzbS5jb21tb24uQ2hhbmdlU3RhdHVzEg4KBm1lbWJlchgCIAEoCRIMCgRuYW1lGAMgASgJIuUBCg9Jbml0Q2hhdFJlcXVlc3QSDQoFbXNnSUQYASABKAMSLAoHbXNnVHlwZRgCIAEoDjIbLmNvbS5zZWMuc3NtLmNvbW1vbi5Nc2dUeXBlEi4KCGNoYXRUeXBlGAMgASgOMhwuY29tLnNlYy5zc20uY29tbW9uLkNoYXRUeXBlEgsKA1VJRBgEIAEoCRIMCgRJTUVJGAUgASgJEhcKD3Jlc2VydmF0aW9uVGltZRgGIAEoAxIOCgZzZW5kZXIYByABKAkSEAoIcmVjZWl2ZXIYCCADKAkSDwoHY2hhdE1zZxgJIAEoCSKqAQoNSW5pdENoYXRSZXBseRINCgVtc2dJRBgBIAEoAxIRCglzZXNzaW9uSUQYAiABKAkSFwoPbXNnUmVjZWl2ZWRUaW1lGAMgASgDEjIKCnNlcnZlckluZm8YBCABKAsyHi5jb20uc2VjLnNzbS5jb21tb24uU2VydmVySW5mbxIqCgZyZXN1bHQYBSABKAsyGi5jb20uc2VjLnNzbS5jb21tb24uUmVzdWx0IqEBChBBbGxvd0NoYXRSZXF1ZXN0Eg0KBW1zZ0lEGAEgASgDEi4KCGNoYXRUeXBlGAIgASgOMhwuY29tLnNlYy5zc20uY29tbW9uLkNoYXRUeXBlEhEKCXNlc3Npb25JRBgDIAEoCRIOCgZzZW5kZXIYBCABKAkSEAoIcmVjZWl2ZXIYBSABKAkSCwoDVUlEGAYgASgJEgwKBElNRUkYByABKAkiSwoOQWxsb3dDaGF0UmVwbHkSDQoFbXNnSUQYASABKAMSKgoGcmVzdWx0GAIgASgLMhouY29tLnNlYy5zc20uY29tbW9uLlJlc3VsdCL0AQoLQ2hhdFJlcXVlc3QSDQoFbXNnSUQYASABKAMSLAoHbXNnVHlwZRgCIAEoDjIbLmNvbS5zZWMuc3NtLmNvbW1vbi5Nc2dUeXBlEi4KCGNoYXRUeXBlGAMgASgOMhwuY29tLnNlYy5zc20uY29tbW9uLkNoYXRUeXBlEhEKCXNlc3Npb25JRBgEIAEoCRIOCgZzZW5kZXIYBSABKAkSEAoIcmVjZWl2ZXIYBiADKAkSCwoDVUlEGAcgASgJEgwKBElNRUkYCCABKAkSDwoHY2hhdE1zZxgJIAEoCRIXCg93aGlzcGVyUmVjZWl2ZXIYCiABKAkipgEKCUNoYXRSZXBseRINCgVtc2dJRBgBIAEoAxIRCglzZXNzaW9uSUQYAiABKAkSMgoKc2VydmVySW5mbxgDIAEoCzIeLmNvbS5zZWMuc3NtLmNvbW1vbi5TZXJ2ZXJJbmZvEhcKD21zZ1JlY2VpdmVkVGltZRgEIAEoAxIqCgZyZXN1bHQYBSABKAsyGi5jb20uc2VjLnNzbS5jb21tb24uUmVzdWx0IrkBCgxEZWxpdmVyeUNoYXQSEQoJc2Vzc2lvbklEGAEgASgJEi4KCGNoYXRUeXBlGAIgASgOMhwuY29tLnNlYy5zc20uY29tbW9uLkNoYXRUeXBlEjYKDGluYm94TWVzc2FnZRgDIAMoCzIgLmNvbS5zZWMuc3NtLmNvbW1vbi5JbmJveE1lc3NhZ2USFwoPd2hpc3BlclJlY2VpdmVyGAQgASgJEhUKDWhhc01vcmVSZXN1bHQYBSABKAgilwEKEURlbGl2ZXJ5Q2hhdFJlcGx5EgsKA1VJRBgBIAEoCRJJChZkZWxpdmVyeUNoYXRSZXBseUl0ZW1zGAIgAygLMikuY29tLnNlYy5zc20uY29tbW9uLkRlbGl2ZXJ5Q2hhdFJlcGx5SXRlbRIqCgZyZXN1bHQYAyABKAsyGi5jb20uc2VjLnNzbS5jb21tb24uUmVzdWx0IpIBCg5FbmRDaGF0UmVxdWVzdBINCgVtc2dJRBgBIAEoAxIuCghjaGF0VHlwZRgCIAEoDjIcLmNvbS5zZWMuc3NtLmNvbW1vbi5DaGF0VHlwZRIRCglzZXNzaW9uSUQYAyABKAkSCwoDVUlEGAQgASgJEg4KBnNlbmRlchgFIAEoCRIRCglyZWNlaXZlcnMYBiADKAkiSQoMRW5kQ2hhdFJlcGx5Eg0KBW1zZ0lEGAEgASgDEioKBnJlc3VsdBgCIAEoCzIaLmNvbS5zZWMuc3NtLmNvbW1vbi5SZXN1bHQiSQoKQW5zd2VyQmFjaxI7Cg9hbnN3ZXJiYWNrSXRlbXMYASADKAsyIi5jb20uc2VjLnNzbS5jb21tb24uQW5zd2VyYmFja0l0ZW0ihwEKD0Fuc3dlckJhY2tSZXBseRILCgNVSUQYASABKAkSOwoPYW5zd2VyYmFja0l0ZW1zGAIgAygLMiIuY29tLnNlYy5zc20uY29tbW9uLkFuc3dlcmJhY2tJdGVtEioKBnJlc3VsdBgDIAEoCzIaLmNvbS5zZWMuc3NtLmNvbW1vbi5SZXN1bHQingEKEUludml0ZUNoYXRSZXF1ZXN0Eg0KBW1zZ0lEGAEgASgDEiwKB21zZ1R5cGUYAiABKA4yGy5jb20uc2VjLnNzbS5jb21tb24uTXNnVHlwZRIRCglzZXNzaW9uSUQYAyABKAkSDgoGc2VuZGVyGAQgASgJEhAKCHJlY2VpdmVyGAUgAygJEhcKD2ludml0aW5nTWVtYmVycxgGIAMoCSJlCg9JbnZpdGVDaGF0UmVwbHkSDQoFbXNnSUQYASABKAMSKgoGcmVzdWx0GAIgASgLMhouY29tLnNlYy5zc20uY29tbW9uLlJlc3VsdBIXCg9tc2dSZWNlaXZlZFRpbWUYAyABKAMicQoRRGlzY29ubmVjdFJlcXVlc3QSDQoFbXNnSUQYASABKAMSOgoOZGlzY29ubmVjdFR5cGUYAiABKA4yIi5jb20uc2VjLnNzbS5jb21tb24uRGlzY29ubmVjdFR5cGUSEQoJc2Vzc2lvbklEGAMgASgJIpQBCg9EaXNjb25uZWN0UmVwbHkSDQoFbXNnSUQYASABKAMSRgoUZGlzY29ubmVjdEFjdGlvblR5cGUYAiABKA4yKC5jb20uc2VjLnNzbS5jb21tb24uRGlzY29ubmVjdEFjdGlvblR5cGUSKgoGcmVzdWx0GAMgASgLMhouY29tLnNlYy5zc20uY29tbW9uLlJlc3VsdCKuAQoOQW5ub3VuY2VDaGFuZ2USDQoFbXNnSUQYASABKAMSEQoJc2Vzc2lvbklEGAIgASgJEj4KEGNoYW5nZU1lbWJlckxpc3QYAyADKAsyJC5jb20uc2VjLnNzbS5jb21tb24uQ2hhbmdlTWVtYmVyTGlzdBIXCg9Hcm91cE1lbWJlckxpc3QYBCADKAkSEAoIc2VudFRpbWUYBSABKAMSDwoHaW52aXRlchgGIAEoCSJQChNBbm5vdW5jZUNoYW5nZVJlcGx5Eg0KBW1zZ0lEGAEgASgDEioKBnJlc3VsdBgCIAEoCzIaLmNvbS5zZWMuc3NtLmNvbW1vbi5SZXN1bHQiLgoPTmlja25hbWVSZXF1ZXN0Eg0KBW1zZ0lEGAEgASgDEgwKBHVzZXIYAiADKAkiegoNTmlja25hbWVSZXBseRINCgVtc2dJRBgBIAEoAxIuCghuaWNrbmFtZRgCIAMoCzIcLmNvbS5zZWMuc3NtLmNvbW1vbi5OaWNrbmFtZRIqCgZyZXN1bHQYAyABKAsyGi5jb20uc2VjLnNzbS5jb21tb24uUmVzdWx0ImIKE1dlYlByb3Zpc2lvblJlcXVlc3QSDQoFbXNnSUQYASABKAMSCwoDVUlEGAIgASgJEgwKBElNRUkYAyABKAkSEAoIcmVjZWl2ZXIYBCABKAkSDwoHY2hhdE1zZxgFIAEoCSJbChFXZWJQcm92aXNpb25SZXBseRINCgVtc2dJRBgBIAEoAxILCgNVSUQYAiABKAkSKgoGcmVzdWx0GAMgASgLMhouY29tLnNlYy5zc20uY29tbW9uLlJlc3VsdCIyChJJbnZhbGlkVXNlclJlcXVlc3QSDQoFbXNnSUQYASABKAMSDQoFdXNlcnMYAiADKAkiYwoQSW52YWxpZFVzZXJSZXBseRINCgVtc2dJRBgBIAEoAxIUCgxpbnZhbGlkVXNlcnMYAiADKAkSKgoGcmVzdWx0GAMgASgLMhouY29tLnNlYy5zc20uY29tbW9uLlJlc3VsdCJeChdTeXN0ZW1fUmVhZHlUb1Rlcm1pbmF0ZRIQCghkYkJhY2t1cBgBIAEoCBIXCg9jb25uZWN0aW9uQ2xvc2UYAiABKAgSGAoQdGVybWluYXRlUHJvY2VzcxgDIAEoCCowCghDaGF0VHlwZRIKCgZTSU5HTEUQABIJCgVHUk9VUBABEg0KCUJST0FEQ0FTVBACKjEKB01zZ1R5cGUSCAoEVEVYVBAAEgkKBU1FRElBEAESCAoETk9USRACEgcKA0FOUxADKjAKDkRpc2Nvbm5lY3RUeXBlEgsKB1RJTUVPVVQQABIRCg1HUk9VUENIQVRfRU5EEAEqLgoURGlzY29ubmVjdEFjdGlvblR5cGUSCQoFQ0xPU0UQABILCgdIT0xEX09OEAEqJAoMQ2hhbmdlU3RhdHVzEgkKBUVOVEVSEAASCQoFTEVBVkUQAUIcChJjb20uc2VjLnNzbS5jb21tb25CBlNTTUdQQg==");
		FileDescriptor.InternalDescriptorAssigner descriptorAssigner = delegate(FileDescriptor root)
		{
			descriptor = root;
			internal__static_com_sec_ssm_common_Result__Descriptor = Descriptor.MessageTypes[0];
			internal__static_com_sec_ssm_common_Result__FieldAccessorTable = new FieldAccessorTable<Result, Result.Builder>(internal__static_com_sec_ssm_common_Result__Descriptor, new string[2] { "ResultCode", "ResultMsg" });
			internal__static_com_sec_ssm_common_Nickname__Descriptor = Descriptor.MessageTypes[1];
			internal__static_com_sec_ssm_common_Nickname__FieldAccessorTable = new FieldAccessorTable<Nickname, Nickname.Builder>(internal__static_com_sec_ssm_common_Nickname__Descriptor, new string[2] { "User", "Nickname_" });
			internal__static_com_sec_ssm_common_InboxMessage__Descriptor = Descriptor.MessageTypes[2];
			internal__static_com_sec_ssm_common_InboxMessage__FieldAccessorTable = new FieldAccessorTable<InboxMessage, InboxMessage.Builder>(internal__static_com_sec_ssm_common_InboxMessage__Descriptor, new string[7] { "Sender", "Receivers", "MsgID", "ChatMsg", "SentTime", "MsgType", "ChatType" });
			internal__static_com_sec_ssm_common_DeliveryChatReplyItem__Descriptor = Descriptor.MessageTypes[3];
			internal__static_com_sec_ssm_common_DeliveryChatReplyItem__FieldAccessorTable = new FieldAccessorTable<DeliveryChatReplyItem, DeliveryChatReplyItem.Builder>(internal__static_com_sec_ssm_common_DeliveryChatReplyItem__Descriptor, new string[4] { "Sender", "Receiver", "MsgID", "MsgType" });
			internal__static_com_sec_ssm_common_AnswerbackItem__Descriptor = Descriptor.MessageTypes[4];
			internal__static_com_sec_ssm_common_AnswerbackItem__FieldAccessorTable = new FieldAccessorTable<AnswerbackItem, AnswerbackItem.Builder>(internal__static_com_sec_ssm_common_AnswerbackItem__Descriptor, new string[2] { "Receiver", "MsgID" });
			internal__static_com_sec_ssm_common_ServerInfo__Descriptor = Descriptor.MessageTypes[5];
			internal__static_com_sec_ssm_common_ServerInfo__FieldAccessorTable = new FieldAccessorTable<ServerInfo, ServerInfo.Builder>(internal__static_com_sec_ssm_common_ServerInfo__Descriptor, new string[2] { "Address", "Port" });
			internal__static_com_sec_ssm_common_ChangeMemberList__Descriptor = Descriptor.MessageTypes[6];
			internal__static_com_sec_ssm_common_ChangeMemberList__FieldAccessorTable = new FieldAccessorTable<ChangeMemberList, ChangeMemberList.Builder>(internal__static_com_sec_ssm_common_ChangeMemberList__Descriptor, new string[3] { "Status", "Member", "Name" });
			internal__static_com_sec_ssm_common_InitChatRequest__Descriptor = Descriptor.MessageTypes[7];
			internal__static_com_sec_ssm_common_InitChatRequest__FieldAccessorTable = new FieldAccessorTable<InitChatRequest, InitChatRequest.Builder>(internal__static_com_sec_ssm_common_InitChatRequest__Descriptor, new string[9] { "MsgID", "MsgType", "ChatType", "UID", "IMEI", "ReservationTime", "Sender", "Receiver", "ChatMsg" });
			internal__static_com_sec_ssm_common_InitChatReply__Descriptor = Descriptor.MessageTypes[8];
			internal__static_com_sec_ssm_common_InitChatReply__FieldAccessorTable = new FieldAccessorTable<InitChatReply, InitChatReply.Builder>(internal__static_com_sec_ssm_common_InitChatReply__Descriptor, new string[5] { "MsgID", "SessionID", "MsgReceivedTime", "ServerInfo", "Result" });
			internal__static_com_sec_ssm_common_AllowChatRequest__Descriptor = Descriptor.MessageTypes[9];
			internal__static_com_sec_ssm_common_AllowChatRequest__FieldAccessorTable = new FieldAccessorTable<AllowChatRequest, AllowChatRequest.Builder>(internal__static_com_sec_ssm_common_AllowChatRequest__Descriptor, new string[7] { "MsgID", "ChatType", "SessionID", "Sender", "Receiver", "UID", "IMEI" });
			internal__static_com_sec_ssm_common_AllowChatReply__Descriptor = Descriptor.MessageTypes[10];
			internal__static_com_sec_ssm_common_AllowChatReply__FieldAccessorTable = new FieldAccessorTable<AllowChatReply, AllowChatReply.Builder>(internal__static_com_sec_ssm_common_AllowChatReply__Descriptor, new string[2] { "MsgID", "Result" });
			internal__static_com_sec_ssm_common_ChatRequest__Descriptor = Descriptor.MessageTypes[11];
			internal__static_com_sec_ssm_common_ChatRequest__FieldAccessorTable = new FieldAccessorTable<ChatRequest, ChatRequest.Builder>(internal__static_com_sec_ssm_common_ChatRequest__Descriptor, new string[10] { "MsgID", "MsgType", "ChatType", "SessionID", "Sender", "Receiver", "UID", "IMEI", "ChatMsg", "WhisperReceiver" });
			internal__static_com_sec_ssm_common_ChatReply__Descriptor = Descriptor.MessageTypes[12];
			internal__static_com_sec_ssm_common_ChatReply__FieldAccessorTable = new FieldAccessorTable<ChatReply, ChatReply.Builder>(internal__static_com_sec_ssm_common_ChatReply__Descriptor, new string[5] { "MsgID", "SessionID", "ServerInfo", "MsgReceivedTime", "Result" });
			internal__static_com_sec_ssm_common_DeliveryChat__Descriptor = Descriptor.MessageTypes[13];
			internal__static_com_sec_ssm_common_DeliveryChat__FieldAccessorTable = new FieldAccessorTable<DeliveryChat, DeliveryChat.Builder>(internal__static_com_sec_ssm_common_DeliveryChat__Descriptor, new string[5] { "SessionID", "ChatType", "InboxMessage", "WhisperReceiver", "HasMoreResult" });
			internal__static_com_sec_ssm_common_DeliveryChatReply__Descriptor = Descriptor.MessageTypes[14];
			internal__static_com_sec_ssm_common_DeliveryChatReply__FieldAccessorTable = new FieldAccessorTable<DeliveryChatReply, DeliveryChatReply.Builder>(internal__static_com_sec_ssm_common_DeliveryChatReply__Descriptor, new string[3] { "UID", "DeliveryChatReplyItems", "Result" });
			internal__static_com_sec_ssm_common_EndChatRequest__Descriptor = Descriptor.MessageTypes[15];
			internal__static_com_sec_ssm_common_EndChatRequest__FieldAccessorTable = new FieldAccessorTable<EndChatRequest, EndChatRequest.Builder>(internal__static_com_sec_ssm_common_EndChatRequest__Descriptor, new string[6] { "MsgID", "ChatType", "SessionID", "UID", "Sender", "Receivers" });
			internal__static_com_sec_ssm_common_EndChatReply__Descriptor = Descriptor.MessageTypes[16];
			internal__static_com_sec_ssm_common_EndChatReply__FieldAccessorTable = new FieldAccessorTable<EndChatReply, EndChatReply.Builder>(internal__static_com_sec_ssm_common_EndChatReply__Descriptor, new string[2] { "MsgID", "Result" });
			internal__static_com_sec_ssm_common_AnswerBack__Descriptor = Descriptor.MessageTypes[17];
			internal__static_com_sec_ssm_common_AnswerBack__FieldAccessorTable = new FieldAccessorTable<AnswerBack, AnswerBack.Builder>(internal__static_com_sec_ssm_common_AnswerBack__Descriptor, new string[1] { "AnswerbackItems" });
			internal__static_com_sec_ssm_common_AnswerBackReply__Descriptor = Descriptor.MessageTypes[18];
			internal__static_com_sec_ssm_common_AnswerBackReply__FieldAccessorTable = new FieldAccessorTable<AnswerBackReply, AnswerBackReply.Builder>(internal__static_com_sec_ssm_common_AnswerBackReply__Descriptor, new string[3] { "UID", "AnswerbackItems", "Result" });
			internal__static_com_sec_ssm_common_InviteChatRequest__Descriptor = Descriptor.MessageTypes[19];
			internal__static_com_sec_ssm_common_InviteChatRequest__FieldAccessorTable = new FieldAccessorTable<InviteChatRequest, InviteChatRequest.Builder>(internal__static_com_sec_ssm_common_InviteChatRequest__Descriptor, new string[6] { "MsgID", "MsgType", "SessionID", "Sender", "Receiver", "InvitingMembers" });
			internal__static_com_sec_ssm_common_InviteChatReply__Descriptor = Descriptor.MessageTypes[20];
			internal__static_com_sec_ssm_common_InviteChatReply__FieldAccessorTable = new FieldAccessorTable<InviteChatReply, InviteChatReply.Builder>(internal__static_com_sec_ssm_common_InviteChatReply__Descriptor, new string[3] { "MsgID", "Result", "MsgReceivedTime" });
			internal__static_com_sec_ssm_common_DisconnectRequest__Descriptor = Descriptor.MessageTypes[21];
			internal__static_com_sec_ssm_common_DisconnectRequest__FieldAccessorTable = new FieldAccessorTable<DisconnectRequest, DisconnectRequest.Builder>(internal__static_com_sec_ssm_common_DisconnectRequest__Descriptor, new string[3] { "MsgID", "DisconnectType", "SessionID" });
			internal__static_com_sec_ssm_common_DisconnectReply__Descriptor = Descriptor.MessageTypes[22];
			internal__static_com_sec_ssm_common_DisconnectReply__FieldAccessorTable = new FieldAccessorTable<DisconnectReply, DisconnectReply.Builder>(internal__static_com_sec_ssm_common_DisconnectReply__Descriptor, new string[3] { "MsgID", "DisconnectActionType", "Result" });
			internal__static_com_sec_ssm_common_AnnounceChange__Descriptor = Descriptor.MessageTypes[23];
			internal__static_com_sec_ssm_common_AnnounceChange__FieldAccessorTable = new FieldAccessorTable<AnnounceChange, AnnounceChange.Builder>(internal__static_com_sec_ssm_common_AnnounceChange__Descriptor, new string[6] { "MsgID", "SessionID", "ChangeMemberList", "GroupMemberList", "SentTime", "Inviter" });
			internal__static_com_sec_ssm_common_AnnounceChangeReply__Descriptor = Descriptor.MessageTypes[24];
			internal__static_com_sec_ssm_common_AnnounceChangeReply__FieldAccessorTable = new FieldAccessorTable<AnnounceChangeReply, AnnounceChangeReply.Builder>(internal__static_com_sec_ssm_common_AnnounceChangeReply__Descriptor, new string[2] { "MsgID", "Result" });
			internal__static_com_sec_ssm_common_NicknameRequest__Descriptor = Descriptor.MessageTypes[25];
			internal__static_com_sec_ssm_common_NicknameRequest__FieldAccessorTable = new FieldAccessorTable<NicknameRequest, NicknameRequest.Builder>(internal__static_com_sec_ssm_common_NicknameRequest__Descriptor, new string[2] { "MsgID", "User" });
			internal__static_com_sec_ssm_common_NicknameReply__Descriptor = Descriptor.MessageTypes[26];
			internal__static_com_sec_ssm_common_NicknameReply__FieldAccessorTable = new FieldAccessorTable<NicknameReply, NicknameReply.Builder>(internal__static_com_sec_ssm_common_NicknameReply__Descriptor, new string[3] { "MsgID", "Nickname", "Result" });
			internal__static_com_sec_ssm_common_WebProvisionRequest__Descriptor = Descriptor.MessageTypes[27];
			internal__static_com_sec_ssm_common_WebProvisionRequest__FieldAccessorTable = new FieldAccessorTable<WebProvisionRequest, WebProvisionRequest.Builder>(internal__static_com_sec_ssm_common_WebProvisionRequest__Descriptor, new string[5] { "MsgID", "UID", "IMEI", "Receiver", "ChatMsg" });
			internal__static_com_sec_ssm_common_WebProvisionReply__Descriptor = Descriptor.MessageTypes[28];
			internal__static_com_sec_ssm_common_WebProvisionReply__FieldAccessorTable = new FieldAccessorTable<WebProvisionReply, WebProvisionReply.Builder>(internal__static_com_sec_ssm_common_WebProvisionReply__Descriptor, new string[3] { "MsgID", "UID", "Result" });
			internal__static_com_sec_ssm_common_InvalidUserRequest__Descriptor = Descriptor.MessageTypes[29];
			internal__static_com_sec_ssm_common_InvalidUserRequest__FieldAccessorTable = new FieldAccessorTable<InvalidUserRequest, InvalidUserRequest.Builder>(internal__static_com_sec_ssm_common_InvalidUserRequest__Descriptor, new string[2] { "MsgID", "Users" });
			internal__static_com_sec_ssm_common_InvalidUserReply__Descriptor = Descriptor.MessageTypes[30];
			internal__static_com_sec_ssm_common_InvalidUserReply__FieldAccessorTable = new FieldAccessorTable<InvalidUserReply, InvalidUserReply.Builder>(internal__static_com_sec_ssm_common_InvalidUserReply__Descriptor, new string[3] { "MsgID", "InvalidUsers", "Result" });
			internal__static_com_sec_ssm_common_System_ReadyToTerminate__Descriptor = Descriptor.MessageTypes[31];
			internal__static_com_sec_ssm_common_System_ReadyToTerminate__FieldAccessorTable = new FieldAccessorTable<System_ReadyToTerminate, System_ReadyToTerminate.Builder>(internal__static_com_sec_ssm_common_System_ReadyToTerminate__Descriptor, new string[3] { "DbBackup", "ConnectionClose", "TerminateProcess" });
			return (ExtensionRegistry)null;
		};
		FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData, new FileDescriptor[0], descriptorAssigner);
	}
}
