package com.sec.chaton.p027e;

import com.sec.common.util.C3364o;

/* compiled from: DatabaseHelper.java */
/* renamed from: com.sec.chaton.e.ba */
/* loaded from: classes.dex */
public interface InterfaceC1425ba {

    /* renamed from: a */
    public static final String f5292a = C3364o.m11849a("(", "SELECT ", "_id", ",", "inbox_no", ",", "inbox_chat_type", ",", "inbox_last_message", ",", "inbox_title", ",", "inbox_title_fixed", ",", "inbox_last_time", ",", "inbox_lang_from", ",", "inbox_unread_count", ",", "inbox_lang_to", ",", "inbox_translated", ",", "inbox_server_ip", ",", "inbox_server_port", ",", "inbox_participants", ",", "inbox_session_id", ",", "inbox_last_msg_no", ",", "inbox_last_msg_sender", ",", "inbox_last_temp_msg", ",", "inbox_last_chat_type", ",", "inbox_is_new", ",", "inbox_trunk_unread_count", ",", "inbox_valid", ",", "buddy_no", ",", "inbox_enable_noti", ",", "inbox_is_change_skin", ",", "inbox_background_style", ",", "inbox_send_bubble_style", ",", "inbox_receive_bubble_style", ",", "inbox_last_tid", ",", "inbox_enable_translate", ",", "translate_outgoing_message", ",", "inbox_translate_my_language", ",", "inbox_translate_buddy_language", ",", "inbox_is_entered", ",", "inbox_last_timestamp", ",", "inbox_web_url", ",", "buddy_status_message", ",", "weburl", ",", "lasst_session_merge_time", ",", "buddy_name", " FROM ", "(", "SELECT ", "*", " FROM ", "inbox", " a", " LEFT OUTER JOIN ", "(", "SELECT ", "buddy_no", ",", "buddy_name", ",", "buddy_status_message", ",", "''", " AS ", "weburl", " FROM ", "buddy", " UNION ALL ", "SELECT ", "buddy_no", " AS ", "buddy_no", ",", "buddy_name", " AS ", "buddy_name", ",", "msgstatus", " AS ", "buddy_status_message", ",", "weburl", " FROM ", "specialbuddy", " UNION ALL ", "SELECT ", "participants_buddy_no", " AS ", "buddy_no", ",", "ifnull(", "MAX", "(", "participants_buddy_name", ")", ",", "participants_buddy_no", ")", " AS ", "buddy_name", ",", "''", " AS ", "buddy_status_message", ",", "''", " AS ", "weburl", " FROM ", "participant", " WHERE ", "participants_buddy_no", " NOT IN ", "(SELECT ", "buddy_no", " FROM ", "buddy", " UNION ALL ", "SELECT ", "buddy_no", " AS ", "buddy_no", " FROM ", "specialbuddy", ")", " GROUP BY ", "participants_buddy_no", ")", " b", " ON ", "b.", "buddy_no", " = ( SELECT ", "buddy_no", " FROM ", "inbox_buddy_relation", " WHERE ", "inbox_no", " = ", "a.", "inbox_no", " ) ", ")", ")");

    /* renamed from: b */
    public static final String f5293b = C3364o.m11849a("SELECT ", "a.*, ", "r.", "buddy_no", " AS ", "relation_buddy_no", "\tFROM ( ", " SELECT ", "j.", "buddy_no", ", ", "j.", "buddy_name", ", ", "i.*", " FROM ", "inbox", " i", " LEFT OUTER JOIN ", "( ", "SELECT ", "p.", "participants_buddy_no", " AS ", "buddy_no", ", ", "ifnull(", "b.", "buddy_name", ", ", "p.", "participants_buddy_name", ")", " AS ", "buddy_name", ",", "p.", "participants_inbox_no", " FROM ", "participant", " p", " LEFT OUTER JOIN ", "buddy", " b ", " ON ", "p.", "participants_buddy_no", " = ", "b.", "buddy_no", " WHERE ", "p.", "participants_inbox_no", " NOT null", " ) j ", " ON ", "i.", "inbox_no", " = ", "j.", "participants_inbox_no", " WHERE ", "i.", "inbox_last_chat_type", " != ", 12, " AND ", "i.", "inbox_valid", " = '", "Y", "' ", " AND ", "i.", "inbox_no", " != ?", " AND ", "i.", "inbox_web_url", " IS null", " GROUP BY ", "i.", "inbox_no", " ) a ", " LEFT OUTER JOIN ", "inbox_buddy_relation", " r ", " ON ", "a.", "inbox_no", " = ", "r.", "inbox_no", " ORDER BY ", "inbox_last_time", " DESC, a._id");

    /* renamed from: c */
    public static final String f5294c = C3364o.m11849a("SELECT ", "a.*, ", "r.", "buddy_no", " AS ", "relation_buddy_no", "\tFROM ( ", " SELECT ", "j.", "buddy_no", ", ", "j.", "buddy_name", ", ", "i.*", " FROM ", "inbox", " i", " LEFT OUTER JOIN ", "( ", "SELECT ", "p.", "participants_buddy_no", " AS ", "buddy_no", ", ", "ifnull(", "b.", "buddy_name", ", ", "p.", "participants_buddy_name", ")", " AS ", "buddy_name", ",", "p.", "participants_inbox_no", " FROM ", "participant", " p", " LEFT OUTER JOIN ", "buddy", " b ", " ON ", "p.", "participants_buddy_no", " = ", "b.", "buddy_no", " WHERE ", "p.", "participants_inbox_no", " NOT null", " ) j ", " ON ", "i.", "inbox_no", " = ", "j.", "participants_inbox_no", " WHERE ", "i.", "inbox_last_chat_type", " != ", 12, " AND ", "i.", "inbox_valid", " = '", "Y", "' ", " AND ", "i.", "inbox_web_url", " IS null", " AND ", "i.", "inbox_chat_type", " != ", Integer.valueOf(EnumC1450r.BROADCAST.m6342a()), " GROUP BY ", "i.", "inbox_no", " ) a ", " LEFT OUTER JOIN ", "inbox_buddy_relation", " r ", " ON ", "a.", "inbox_no", " = ", "r.", "inbox_no", " ORDER BY ", "inbox_last_time", " DESC, a._id DESC");

    /* renamed from: d */
    public static final String f5295d = C3364o.m11849a("(", "SELECT ", "c.", "participants_buddy_name", " AS ", "inbox_title", ",", "a.", "inbox_no", " FROM ", "inbox", " a,", "(", "SELECT ", "participants_inbox_no", ",", "group_concat(", "participants_buddy_name", ", \", \") AS ", "participants_buddy_name", " FROM ", "(", "SELECT ", "ifnull(", "b.", "buddy_name", ",", "MAX(", "p.", "participants_buddy_name", ")) AS ", "participants_buddy_name", ",", "p.", "participants_buddy_no", ",", "p.", "participants_inbox_no", ",", "p.", "rowid", " FROM ", "participant", " p", " LEFT OUTER JOIN ", "( ", "SELECT ", "buddy_no", ", ", "buddy_name", " FROM ", "buddy", " UNION ALL ", "SELECT ", "buddy_no", " AS ", "buddy_no", ", ", "buddy_name", " AS ", "buddy_name", " FROM ", "specialbuddy", " )", " b", " ON ", "p.", "participants_buddy_no", "=", "b.", "buddy_no", " GROUP BY ", "p.", "participants_buddy_no", ",", "p.", "participants_inbox_no", " ORDER BY ", "p.", "rowid", " DESC", ") ", " GROUP BY ", "participants_inbox_no", ") c", " WHERE ", "a.", "inbox_no", "=", "c.", "participants_inbox_no", " AND (", "a.", "inbox_chat_type", "=", Integer.valueOf(EnumC1450r.GROUPCHAT.m6342a()), " OR ", "a.", "inbox_chat_type", "=", Integer.valueOf(EnumC1450r.ONETOONE.m6342a()), ") AND ", "a.", "inbox_title_fixed", "=", "'", "N", "'", ")");
}
